<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260924133000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add controlled download catalogue, versions, mirrors, dependencies and modpack manifests';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            "CREATE TABLE download_package (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL, type VARCHAR(20) NOT NULL, visibility VARCHAR(20) NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))",
        );
        $this->addSql('CREATE UNIQUE INDEX uniq_download_package_slug ON download_package (slug)');

        $this->addSql(
            "CREATE TABLE download_version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, package_id INT NOT NULL, replaced_by_id INT DEFAULT NULL, version VARCHAR(80) NOT NULL, safe_filename VARCHAR(255) NOT NULL, sha256 VARCHAR(64) NOT NULL, scan_status VARCHAR(20) NOT NULL, scan_attempts INT DEFAULT 0 NOT NULL, last_scanned_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, scan_error VARCHAR(64) DEFAULT NULL, storage_reference VARCHAR(500) NOT NULL, compatibility JSON NOT NULL, changelog TEXT DEFAULT NULL, obsolete BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))",
        );
        $this->addSql('CREATE INDEX IDX_DOWNLOAD_VERSION_PACKAGE ON download_version (package_id)');
        $this->addSql('CREATE INDEX IDX_DOWNLOAD_VERSION_REPLACED_BY ON download_version (replaced_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_download_package_version ON download_version (package_id, version)');
        $this->addSql("COMMENT ON COLUMN download_version.compatibility IS '(DC2Type:json)'");
        $this->addSql("COMMENT ON COLUMN download_version.last_scanned_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql(
            'ALTER TABLE download_version ADD CONSTRAINT FK_DOWNLOAD_VERSION_PACKAGE FOREIGN KEY (package_id) REFERENCES download_package (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE',
        );
        $this->addSql(
            'ALTER TABLE download_version ADD CONSTRAINT FK_DOWNLOAD_VERSION_REPLACED_BY FOREIGN KEY (replaced_by_id) REFERENCES download_version (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE',
        );

        $this->addSql(
            "CREATE TABLE download_dependency (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_id INT NOT NULL, target_package_id INT NOT NULL, kind VARCHAR(20) NOT NULL, constraint_expression VARCHAR(80) DEFAULT NULL, PRIMARY KEY(id))",
        );
        $this->addSql('CREATE INDEX IDX_DOWNLOAD_DEPENDENCY_VERSION ON download_dependency (version_id)');
        $this->addSql('CREATE INDEX IDX_DOWNLOAD_DEPENDENCY_TARGET ON download_dependency (target_package_id)');
        $this->addSql(
            'ALTER TABLE download_dependency ADD CONSTRAINT FK_DOWNLOAD_DEPENDENCY_VERSION FOREIGN KEY (version_id) REFERENCES download_version (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE',
        );
        $this->addSql(
            'ALTER TABLE download_dependency ADD CONSTRAINT FK_DOWNLOAD_DEPENDENCY_TARGET FOREIGN KEY (target_package_id) REFERENCES download_package (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE',
        );

        $this->addSql(
            "CREATE TABLE download_mirror (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_id INT NOT NULL, url VARCHAR(500) NOT NULL, trusted BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))",
        );
        $this->addSql('CREATE INDEX IDX_DOWNLOAD_MIRROR_VERSION ON download_mirror (version_id)');
        $this->addSql(
            'ALTER TABLE download_mirror ADD CONSTRAINT FK_DOWNLOAD_MIRROR_VERSION FOREIGN KEY (version_id) REFERENCES download_version (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE',
        );

        $this->addSql(
            "CREATE TABLE download_manifest_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, modpack_version_id INT NOT NULL, package_id INT NOT NULL, version_constraint VARCHAR(80) NOT NULL, required BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))",
        );
        $this->addSql('CREATE INDEX IDX_DOWNLOAD_MANIFEST_VERSION ON download_manifest_entry (modpack_version_id)');
        $this->addSql('CREATE INDEX IDX_DOWNLOAD_MANIFEST_PACKAGE ON download_manifest_entry (package_id)');
        $this->addSql(
            'CREATE UNIQUE INDEX uniq_download_manifest_item ON download_manifest_entry (modpack_version_id, package_id)',
        );
        $this->addSql(
            'ALTER TABLE download_manifest_entry ADD CONSTRAINT FK_DOWNLOAD_MANIFEST_VERSION FOREIGN KEY (modpack_version_id) REFERENCES download_version (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE',
        );
        $this->addSql(
            'ALTER TABLE download_manifest_entry ADD CONSTRAINT FK_DOWNLOAD_MANIFEST_PACKAGE FOREIGN KEY (package_id) REFERENCES download_package (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE download_manifest_entry');
        $this->addSql('DROP TABLE download_mirror');
        $this->addSql('DROP TABLE download_dependency');
        $this->addSql('DROP TABLE download_version');
        $this->addSql('DROP TABLE download_package');
    }
}
