<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260925010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add isolated versioned game knowledge, map helpers, private checklists and correction moderation';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE game_knowledge_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, record_type VARCHAR(24) NOT NULL, record_key VARCHAR(160) NOT NULL, version INT NOT NULL, attributes JSON NOT NULL, source VARCHAR(500) NOT NULL, license VARCHAR(160) NOT NULL, published BOOLEAN NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAME_KNOWLEDGE_VERSION ON game_knowledge_record (game_id, record_key, version)');
        $this->addSql('ALTER TABLE game_knowledge_record ADD CONSTRAINT FK_GAME_KNOWLEDGE_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE game_knowledge_relationship (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, from_key VARCHAR(160) NOT NULL, relation_type VARCHAR(24) NOT NULL, to_key VARCHAR(160) NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAME_KNOWLEDGE_RELATION ON game_knowledge_relationship (game_id, from_key, relation_type, to_key)');
        $this->addSql('ALTER TABLE game_knowledge_relationship ADD CONSTRAINT FK_GAME_KNOWLEDGE_REL_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE game_knowledge_marker (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, layer_key VARCHAR(120) NOT NULL, marker_key VARCHAR(160) NOT NULL, position_x DOUBLE PRECISION NOT NULL, position_y DOUBLE PRECISION NOT NULL, visibility VARCHAR(16) NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAME_KNOWLEDGE_MARKER ON game_knowledge_marker (game_id, layer_key, marker_key)');
        $this->addSql('ALTER TABLE game_knowledge_marker ADD CONSTRAINT FK_GAME_KNOWLEDGE_MARKER_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE game_knowledge_route (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, route_key VARCHAR(160) NOT NULL, points JSON NOT NULL, visibility VARCHAR(16) NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAME_KNOWLEDGE_ROUTE ON game_knowledge_route (game_id, route_key)');
        $this->addSql('ALTER TABLE game_knowledge_route ADD CONSTRAINT FK_GAME_KNOWLEDGE_ROUTE_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE game_knowledge_checklist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, owner_id INT NOT NULL, record_key VARCHAR(160) NOT NULL, completed BOOLEAN NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAME_KNOWLEDGE_CHECKLIST ON game_knowledge_checklist (game_id, owner_id, record_key)');
        $this->addSql('ALTER TABLE game_knowledge_checklist ADD CONSTRAINT FK_GAME_KNOWLEDGE_CHECKLIST_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_knowledge_checklist ADD CONSTRAINT FK_GAME_KNOWLEDGE_CHECKLIST_OWNER FOREIGN KEY (owner_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE game_knowledge_correction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, proposer_id INT DEFAULT NULL, reviewer_id INT DEFAULT NULL, record_key VARCHAR(160) NOT NULL, proposal TEXT NOT NULL, source VARCHAR(500) NOT NULL, license VARCHAR(160) NOT NULL, status VARCHAR(16) NOT NULL, decision_reason VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_GAME_KNOWLEDGE_CORRECTION ON game_knowledge_correction (game_id, status)');
        $this->addSql('ALTER TABLE game_knowledge_correction ADD CONSTRAINT FK_GAME_KNOWLEDGE_CORRECTION_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_knowledge_correction ADD CONSTRAINT FK_GAME_KNOWLEDGE_CORRECTION_PROPOSER FOREIGN KEY (proposer_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_knowledge_correction ADD CONSTRAINT FK_GAME_KNOWLEDGE_CORRECTION_REVIEWER FOREIGN KEY (reviewer_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(true, 'Knowledge provenance, private checklist and correction audit data require export and Trusted-approved restore handling before downgrade.');
    }
}
