<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260916233000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add video module, categories, playlists, sources, scheduling and public module toggle';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');

        $this->addSql('ALTER TABLE site_settings ADD video_enabled BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('CREATE TABLE video_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, description TEXT DEFAULT NULL, enabled BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_video_category_slug ON video_category (slug)');
        $this->addSql('CREATE TABLE video_playlist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, enabled BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_video_playlist_slug ON video_playlist (slug)');
        $this->addSql('CREATE TABLE video (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category_id INT DEFAULT NULL, media_asset_id INT DEFAULT NULL, title VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL, description TEXT NOT NULL, source_type VARCHAR(12) NOT NULL, source_url VARCHAR(700) DEFAULT NULL, thumbnail_url VARCHAR(700) DEFAULT NULL, duration_label VARCHAR(40) DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, enabled BOOLEAN DEFAULT true NOT NULL, featured BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_video_slug ON video (slug)');
        $this->addSql('CREATE INDEX IDX_VIDEO_CATEGORY ON video (category_id)');
        $this->addSql('CREATE INDEX IDX_VIDEO_MEDIA ON video (media_asset_id)');
        $this->addSql('ALTER TABLE video ADD CONSTRAINT FK_VIDEO_CATEGORY FOREIGN KEY (category_id) REFERENCES video_category (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video ADD CONSTRAINT FK_VIDEO_MEDIA FOREIGN KEY (media_asset_id) REFERENCES media_asset (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN video.published_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN video.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('CREATE TABLE video_video_playlist (video_id INT NOT NULL, video_playlist_id INT NOT NULL, PRIMARY KEY(video_id, video_playlist_id))');
        $this->addSql('CREATE INDEX IDX_VIDEO_PLAYLIST_VIDEO ON video_video_playlist (video_id)');
        $this->addSql('CREATE INDEX IDX_VIDEO_PLAYLIST_LIST ON video_video_playlist (video_playlist_id)');
        $this->addSql('ALTER TABLE video_video_playlist ADD CONSTRAINT FK_VIDEO_PLAYLIST_VIDEO FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_video_playlist ADD CONSTRAINT FK_VIDEO_PLAYLIST_LIST FOREIGN KEY (video_playlist_id) REFERENCES video_playlist (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE video_video_playlist');
        $this->addSql('DROP TABLE video');
        $this->addSql('DROP TABLE video_playlist');
        $this->addSql('DROP TABLE video_category');
        $this->addSql('ALTER TABLE site_settings DROP video_enabled');
    }
}
