<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260925070000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add competitions, seasons, registrations, brackets, match evidence and disputes';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE competition_season (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, name VARCHAR(180) NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(20) NOT NULL, archived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_COMPETITION_SEASON_GAME ON competition_season (game_id)');
        $this->addSql('ALTER TABLE competition_season ADD CONSTRAINT FK_COMPETITION_SEASON_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN competition_season.starts_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN competition_season.ends_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN competition_season.archived_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN competition_season.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE competition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, season_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, name VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL, description TEXT NOT NULL, format VARCHAR(30) NOT NULL, mode VARCHAR(12) NOT NULL, status VARCHAR(20) NOT NULL, visibility VARCHAR(12) NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, check_in_deadline TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, max_participants INT DEFAULT NULL, team_size INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_competition_slug ON competition (slug)');
        $this->addSql('CREATE INDEX IDX_COMPETITION_GAME ON competition (game_id)');
        $this->addSql('CREATE INDEX IDX_COMPETITION_SEASON ON competition (season_id)');
        $this->addSql('CREATE INDEX IDX_COMPETITION_CREATED_BY ON competition (created_by_id)');
        $this->addSql('ALTER TABLE competition ADD CONSTRAINT FK_COMPETITION_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competition ADD CONSTRAINT FK_COMPETITION_SEASON FOREIGN KEY (season_id) REFERENCES competition_season (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competition ADD CONSTRAINT FK_COMPETITION_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN competition.starts_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN competition.ends_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN competition.check_in_deadline IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN competition.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE competition_participant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, competition_id INT NOT NULL, captain_id INT NOT NULL, name VARCHAR(180) NOT NULL, kind VARCHAR(12) NOT NULL, status VARCHAR(20) NOT NULL, seed INT DEFAULT NULL, roster_user_ids JSON NOT NULL, status_reason TEXT DEFAULT NULL, registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, check_in_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_competition_participant_name ON competition_participant (competition_id, name)');
        $this->addSql('CREATE INDEX IDX_COMPETITION_PARTICIPANT_COMPETITION ON competition_participant (competition_id)');
        $this->addSql('CREATE INDEX IDX_COMPETITION_PARTICIPANT_CAPTAIN ON competition_participant (captain_id)');
        $this->addSql('ALTER TABLE competition_participant ADD CONSTRAINT FK_COMPETITION_PARTICIPANT_COMPETITION FOREIGN KEY (competition_id) REFERENCES competition (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competition_participant ADD CONSTRAINT FK_COMPETITION_PARTICIPANT_CAPTAIN FOREIGN KEY (captain_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN competition_participant.registered_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN competition_participant.check_in_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN competition_participant.updated_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE competition_match (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, competition_id INT NOT NULL, round_number INT NOT NULL, bracket VARCHAR(20) NOT NULL, sequence INT NOT NULL, participant_a_id INT DEFAULT NULL, participant_b_id INT DEFAULT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(24) NOT NULL, score_a INT DEFAULT NULL, score_b INT DEFAULT NULL, winner_id INT DEFAULT NULL, submitted_by_id INT DEFAULT NULL, participant_a_confirmed BOOLEAN DEFAULT false NOT NULL, participant_b_confirmed BOOLEAN DEFAULT false NOT NULL, result_submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_competition_match_slot ON competition_match (competition_id, bracket, round_number, sequence)');
        $this->addSql('CREATE INDEX IDX_COMPETITION_MATCH_COMPETITION ON competition_match (competition_id)');
        $this->addSql('CREATE INDEX IDX_COMPETITION_MATCH_A ON competition_match (participant_a_id)');
        $this->addSql('CREATE INDEX IDX_COMPETITION_MATCH_B ON competition_match (participant_b_id)');
        $this->addSql('CREATE INDEX IDX_COMPETITION_MATCH_WINNER ON competition_match (winner_id)');
        $this->addSql('ALTER TABLE competition_match ADD CONSTRAINT FK_COMPETITION_MATCH_COMPETITION FOREIGN KEY (competition_id) REFERENCES competition (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competition_match ADD CONSTRAINT FK_COMPETITION_MATCH_A FOREIGN KEY (participant_a_id) REFERENCES competition_participant (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competition_match ADD CONSTRAINT FK_COMPETITION_MATCH_B FOREIGN KEY (participant_b_id) REFERENCES competition_participant (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competition_match ADD CONSTRAINT FK_COMPETITION_MATCH_WINNER FOREIGN KEY (winner_id) REFERENCES competition_participant (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competition_match ADD CONSTRAINT FK_COMPETITION_MATCH_SUBMITTED_BY FOREIGN KEY (submitted_by_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN competition_match.scheduled_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN competition_match.result_submitted_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN competition_match.confirmed_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN competition_match.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE competition_match_evidence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, match_id INT NOT NULL, submitted_by_id INT NOT NULL, type VARCHAR(20) NOT NULL, locator VARCHAR(500) NOT NULL, description TEXT DEFAULT NULL, visibility VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_COMPETITION_EVIDENCE_MATCH ON competition_match_evidence (match_id)');
        $this->addSql('CREATE INDEX IDX_COMPETITION_EVIDENCE_SUBMITTED_BY ON competition_match_evidence (submitted_by_id)');
        $this->addSql('ALTER TABLE competition_match_evidence ADD CONSTRAINT FK_COMPETITION_EVIDENCE_MATCH FOREIGN KEY (match_id) REFERENCES competition_match (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competition_match_evidence ADD CONSTRAINT FK_COMPETITION_EVIDENCE_SUBMITTED_BY FOREIGN KEY (submitted_by_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN competition_match_evidence.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE competition_dispute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, match_id INT NOT NULL, opened_by_id INT NOT NULL, decided_by_id INT DEFAULT NULL, status VARCHAR(20) NOT NULL, reason TEXT NOT NULL, decision TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_COMPETITION_DISPUTE_MATCH ON competition_dispute (match_id)');
        $this->addSql('CREATE INDEX IDX_COMPETITION_DISPUTE_OPENED_BY ON competition_dispute (opened_by_id)');
        $this->addSql('CREATE INDEX IDX_COMPETITION_DISPUTE_DECIDED_BY ON competition_dispute (decided_by_id)');
        $this->addSql('ALTER TABLE competition_dispute ADD CONSTRAINT FK_COMPETITION_DISPUTE_MATCH FOREIGN KEY (match_id) REFERENCES competition_match (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competition_dispute ADD CONSTRAINT FK_COMPETITION_DISPUTE_OPENED_BY FOREIGN KEY (opened_by_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competition_dispute ADD CONSTRAINT FK_COMPETITION_DISPUTE_DECIDED_BY FOREIGN KEY (decided_by_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN competition_dispute.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN competition_dispute.decided_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE competition_dispute');
        $this->addSql('DROP TABLE competition_match_evidence');
        $this->addSql('DROP TABLE competition_match');
        $this->addSql('DROP TABLE competition_participant');
        $this->addSql('DROP TABLE competition');
        $this->addSql('DROP TABLE competition_season');
    }
}
