<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260924230000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add isolated transparent editorial scores, revisions and moderated community ratings';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE editorial_score (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content_id INT NOT NULL, score SMALLINT NOT NULL, methodology TEXT NOT NULL, platform VARCHAR(120) NOT NULL, reviewed_version VARCHAR(120) NOT NULL, pros JSON NOT NULL, cons JSON NOT NULL, disclosure TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EDITORIAL_SCORE_CONTENT ON editorial_score (content_id)');
        $this->addSql('ALTER TABLE editorial_score ADD CONSTRAINT FK_EDITORIAL_SCORE_CONTENT FOREIGN KEY (content_id) REFERENCES content_entry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE editorial_revision_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content_id INT NOT NULL, actor_id INT DEFAULT NULL, version INT NOT NULL, summary VARCHAR(500) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EDITORIAL_REVISION_VERSION ON editorial_revision_audit (content_id, version)');
        $this->addSql('ALTER TABLE editorial_revision_audit ADD CONSTRAINT FK_EDITORIAL_REVISION_CONTENT FOREIGN KEY (content_id) REFERENCES content_entry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE editorial_revision_audit ADD CONSTRAINT FK_EDITORIAL_REVISION_ACTOR FOREIGN KEY (actor_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE TABLE editorial_community_rating (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content_id INT NOT NULL, user_id INT NOT NULL, rating SMALLINT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EDITORIAL_RATING_ACCOUNT ON editorial_community_rating (content_id, user_id)');
        $this->addSql('ALTER TABLE editorial_community_rating ADD CONSTRAINT FK_EDITORIAL_RATING_CONTENT FOREIGN KEY (content_id) REFERENCES content_entry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE editorial_community_rating ADD CONSTRAINT FK_EDITORIAL_RATING_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(true, 'Editorial revision and rating audit data requires export and Trusted-approved restore handling before downgrade.');
    }
}
