<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260916203000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add site settings, categories, menu items and content categories';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');

        $this->addSql('CREATE TABLE site_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, site_name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, home_title VARCHAR(180) NOT NULL, home_text TEXT NOT NULL, primary_color VARCHAR(7) NOT NULL, color_scheme VARCHAR(10) NOT NULL, logo_path VARCHAR(255) DEFAULT NULL, favicon_path VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE content_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_content_category_slug ON content_category (slug)');
        $this->addSql('CREATE TABLE menu_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, page_id INT DEFAULT NULL, label VARCHAR(100) NOT NULL, url VARCHAR(500) DEFAULT NULL, position INT NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, open_new_window BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_MENU_ITEM_PAGE ON menu_item (page_id)');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_MENU_ITEM_PAGE FOREIGN KEY (page_id) REFERENCES content_entry (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE content_entry ADD category_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_CONTENT_ENTRY_CATEGORY ON content_entry (category_id)');
        $this->addSql('ALTER TABLE content_entry ADD CONSTRAINT FK_CONTENT_ENTRY_CATEGORY FOREIGN KEY (category_id) REFERENCES content_category (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE content_entry DROP CONSTRAINT FK_CONTENT_ENTRY_CATEGORY');
        $this->addSql('DROP INDEX IDX_CONTENT_ENTRY_CATEGORY');
        $this->addSql('ALTER TABLE content_entry DROP category_id');
        $this->addSql('DROP TABLE menu_item');
        $this->addSql('DROP TABLE content_category');
        $this->addSql('DROP TABLE site_settings');
    }
}
