<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260924170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add privacy-aware video discovery, collections, history, clips and live streams';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE video_discovery_creator (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT DEFAULT NULL, display_name VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL, bio TEXT DEFAULT NULL, visibility VARCHAR(16) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_video_creator_slug ON video_discovery_creator (slug)');
        $this->addSql('CREATE INDEX IDX_VDISC_CREATOR_OWNER ON video_discovery_creator (owner_id)');
        $this->addSql('ALTER TABLE video_discovery_creator ADD CONSTRAINT FK_VDISC_CREATOR_OWNER FOREIGN KEY (owner_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE video_discovery_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_video_discovery_tag_slug ON video_discovery_tag (slug)');

        $this->addSql('CREATE TABLE video_discovery_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, video_id INT NOT NULL, creator_id INT DEFAULT NULL, visibility VARCHAR(16) NOT NULL, discoverable BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_video_discovery_video ON video_discovery_profile (video_id)');
        $this->addSql('CREATE INDEX IDX_VDISC_PROFILE_CREATOR ON video_discovery_profile (creator_id)');
        $this->addSql('ALTER TABLE video_discovery_profile ADD CONSTRAINT FK_VDISC_PROFILE_VIDEO FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_discovery_profile ADD CONSTRAINT FK_VDISC_PROFILE_CREATOR FOREIGN KEY (creator_id) REFERENCES video_discovery_creator (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE video_discovery_profile_tag (profile_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY(profile_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_VDISC_PROFILE_TAG_PROFILE ON video_discovery_profile_tag (profile_id)');
        $this->addSql('CREATE INDEX IDX_VDISC_PROFILE_TAG_TAG ON video_discovery_profile_tag (tag_id)');
        $this->addSql('ALTER TABLE video_discovery_profile_tag ADD CONSTRAINT FK_VDISC_PROFILE_TAG_PROFILE FOREIGN KEY (profile_id) REFERENCES video_discovery_profile (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_discovery_profile_tag ADD CONSTRAINT FK_VDISC_PROFILE_TAG_TAG FOREIGN KEY (tag_id) REFERENCES video_discovery_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE video_discovery_favorite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, video_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_video_favorite_user_video ON video_discovery_favorite (user_id, video_id)');
        $this->addSql('CREATE INDEX IDX_VDISC_FAVORITE_USER ON video_discovery_favorite (user_id)');
        $this->addSql('CREATE INDEX IDX_VDISC_FAVORITE_VIDEO ON video_discovery_favorite (video_id)');
        $this->addSql('ALTER TABLE video_discovery_favorite ADD CONSTRAINT FK_VDISC_FAVORITE_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_discovery_favorite ADD CONSTRAINT FK_VDISC_FAVORITE_VIDEO FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN video_discovery_favorite.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE video_discovery_history_preference (user_id INT NOT NULL, enabled BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(user_id))');
        $this->addSql('ALTER TABLE video_discovery_history_preference ADD CONSTRAINT FK_VDISC_HISTORY_PREF_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE video_discovery_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, video_id INT NOT NULL, watched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, position_seconds INT DEFAULT 0 NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_VDISC_HISTORY_USER_TIME ON video_discovery_history (user_id, watched_at)');
        $this->addSql('CREATE INDEX IDX_VDISC_HISTORY_VIDEO ON video_discovery_history (video_id)');
        $this->addSql('ALTER TABLE video_discovery_history ADD CONSTRAINT FK_VDISC_HISTORY_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_discovery_history ADD CONSTRAINT FK_VDISC_HISTORY_VIDEO FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN video_discovery_history.watched_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE video_discovery_watchlist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, name VARCHAR(120) NOT NULL, public BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_video_watchlist_user_name ON video_discovery_watchlist (user_id, name)');
        $this->addSql('CREATE INDEX IDX_VDISC_WATCHLIST_USER ON video_discovery_watchlist (user_id)');
        $this->addSql('ALTER TABLE video_discovery_watchlist ADD CONSTRAINT FK_VDISC_WATCHLIST_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN video_discovery_watchlist.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE video_discovery_watchlist_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, watchlist_id INT NOT NULL, video_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_video_watchlist_item ON video_discovery_watchlist_item (watchlist_id, video_id)');
        $this->addSql('CREATE INDEX IDX_VDISC_WATCHLIST_ITEM_LIST ON video_discovery_watchlist_item (watchlist_id)');
        $this->addSql('CREATE INDEX IDX_VDISC_WATCHLIST_ITEM_VIDEO ON video_discovery_watchlist_item (video_id)');
        $this->addSql('ALTER TABLE video_discovery_watchlist_item ADD CONSTRAINT FK_VDISC_WATCHLIST_ITEM_LIST FOREIGN KEY (watchlist_id) REFERENCES video_discovery_watchlist (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_discovery_watchlist_item ADD CONSTRAINT FK_VDISC_WATCHLIST_ITEM_VIDEO FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN video_discovery_watchlist_item.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE video_discovery_timestamp_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, author_id INT NOT NULL, video_id INT NOT NULL, timestamp_seconds INT NOT NULL, body TEXT NOT NULL, visibility VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_VDISC_COMMENT_AUTHOR ON video_discovery_timestamp_comment (author_id)');
        $this->addSql('CREATE INDEX idx_video_timestamp_comment_video ON video_discovery_timestamp_comment (video_id, timestamp_seconds, created_at)');
        $this->addSql('ALTER TABLE video_discovery_timestamp_comment ADD CONSTRAINT FK_VDISC_COMMENT_AUTHOR FOREIGN KEY (author_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_discovery_timestamp_comment ADD CONSTRAINT FK_VDISC_COMMENT_VIDEO FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN video_discovery_timestamp_comment.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE video_discovery_clip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, video_id INT NOT NULL, created_by_id INT NOT NULL, title VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL, start_seconds INT NOT NULL, end_seconds INT NOT NULL, visibility VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_video_clip_slug ON video_discovery_clip (slug)');
        $this->addSql('CREATE INDEX IDX_VDISC_CLIP_VIDEO ON video_discovery_clip (video_id)');
        $this->addSql('CREATE INDEX IDX_VDISC_CLIP_CREATOR ON video_discovery_clip (created_by_id)');
        $this->addSql('ALTER TABLE video_discovery_clip ADD CONSTRAINT FK_VDISC_CLIP_VIDEO FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_discovery_clip ADD CONSTRAINT FK_VDISC_CLIP_CREATOR FOREIGN KEY (created_by_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN video_discovery_clip.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE video_discovery_live_stream (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, creator_id INT DEFAULT NULL, title VARCHAR(160) NOT NULL, provider VARCHAR(16) NOT NULL, source_url VARCHAR(700) NOT NULL, consent_mode VARCHAR(24) NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_VDISC_LIVE_CREATOR ON video_discovery_live_stream (creator_id)');
        $this->addSql('ALTER TABLE video_discovery_live_stream ADD CONSTRAINT FK_VDISC_LIVE_CREATOR FOREIGN KEY (creator_id) REFERENCES video_discovery_creator (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN video_discovery_live_stream.starts_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE video_discovery_live_stream');
        $this->addSql('DROP TABLE video_discovery_clip');
        $this->addSql('DROP TABLE video_discovery_timestamp_comment');
        $this->addSql('DROP TABLE video_discovery_watchlist_item');
        $this->addSql('DROP TABLE video_discovery_watchlist');
        $this->addSql('DROP TABLE video_discovery_history');
        $this->addSql('DROP TABLE video_discovery_history_preference');
        $this->addSql('DROP TABLE video_discovery_favorite');
        $this->addSql('DROP TABLE video_discovery_profile_tag');
        $this->addSql('DROP TABLE video_discovery_profile');
        $this->addSql('DROP TABLE video_discovery_tag');
        $this->addSql('DROP TABLE video_discovery_creator');
    }
}
