<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260918141000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Store sanitized latest connector health per capability and target';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('CREATE TABLE external_connector_health_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, capability VARCHAR(40) NOT NULL, target_key VARCHAR(64) NOT NULL, provider_key VARCHAR(64) NOT NULL, successful BOOLEAN NOT NULL, checked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_connector_health_target ON external_connector_health_status (capability, target_key)');
        $this->addSql("COMMENT ON COLUMN external_connector_health_status.checked_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE external_connector_health_status');
    }
}
