<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260917007000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add private member notifications'; }
    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('CREATE TABLE member_notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, guild_id INT NOT NULL, type VARCHAR(60) NOT NULL, title VARCHAR(180) NOT NULL, message TEXT NOT NULL, link VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_MEMBER_NOTIFICATION_USER ON member_notification (user_id)');
        $this->addSql('CREATE INDEX IDX_MEMBER_NOTIFICATION_GUILD ON member_notification (guild_id)');
        $this->addSql('ALTER TABLE member_notification ADD CONSTRAINT FK_MEMBER_NOTIFICATION_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE member_notification ADD CONSTRAINT FK_MEMBER_NOTIFICATION_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN member_notification.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN member_notification.read_at IS '(DC2Type:datetime_immutable)'");
    }
    public function down(Schema $schema): void { $this->addSql('DROP TABLE member_notification'); }
}
