<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260924120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add reusable community comments, reactions, reports and moderation audit tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE community_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, author_id INT NOT NULL, parent_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, target_type VARCHAR(32) NOT NULL, target_id INT NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deletion_reason VARCHAR(500) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_COMMUNITY_COMMENT_AUTHOR ON community_comment (author_id)');
        $this->addSql('CREATE INDEX IDX_COMMUNITY_COMMENT_PARENT ON community_comment (parent_id)');
        $this->addSql('CREATE INDEX IDX_COMMUNITY_COMMENT_DELETED_BY ON community_comment (deleted_by_id)');
        $this->addSql('CREATE INDEX idx_community_comment_target ON community_comment (target_type, target_id, created_at)');
        $this->addSql('ALTER TABLE community_comment ADD CONSTRAINT FK_COMMUNITY_COMMENT_AUTHOR FOREIGN KEY (author_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_comment ADD CONSTRAINT FK_COMMUNITY_COMMENT_PARENT FOREIGN KEY (parent_id) REFERENCES community_comment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_comment ADD CONSTRAINT FK_COMMUNITY_COMMENT_DELETED_BY FOREIGN KEY (deleted_by_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN community_comment.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN community_comment.deleted_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE community_reaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment_id INT NOT NULL, user_id INT NOT NULL, reaction VARCHAR(24) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_COMMUNITY_REACTION_COMMENT ON community_reaction (comment_id)');
        $this->addSql('CREATE INDEX IDX_COMMUNITY_REACTION_USER ON community_reaction (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_community_reaction_actor ON community_reaction (comment_id, user_id, reaction)');
        $this->addSql('ALTER TABLE community_reaction ADD CONSTRAINT FK_COMMUNITY_REACTION_COMMENT FOREIGN KEY (comment_id) REFERENCES community_comment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_reaction ADD CONSTRAINT FK_COMMUNITY_REACTION_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN community_reaction.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE community_report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment_id INT NOT NULL, reporter_id INT NOT NULL, decided_by_id INT DEFAULT NULL, reason VARCHAR(32) NOT NULL, details TEXT DEFAULT NULL, status VARCHAR(16) NOT NULL, decision_reason VARCHAR(1000) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_COMMUNITY_REPORT_COMMENT ON community_report (comment_id)');
        $this->addSql('CREATE INDEX IDX_COMMUNITY_REPORT_REPORTER ON community_report (reporter_id)');
        $this->addSql('CREATE INDEX IDX_COMMUNITY_REPORT_DECIDED_BY ON community_report (decided_by_id)');
        $this->addSql('CREATE INDEX idx_community_report_queue ON community_report (status, created_at)');
        $this->addSql('ALTER TABLE community_report ADD CONSTRAINT FK_COMMUNITY_REPORT_COMMENT FOREIGN KEY (comment_id) REFERENCES community_comment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_report ADD CONSTRAINT FK_COMMUNITY_REPORT_REPORTER FOREIGN KEY (reporter_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE community_report ADD CONSTRAINT FK_COMMUNITY_REPORT_DECIDED_BY FOREIGN KEY (decided_by_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN community_report.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN community_report.decided_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE community_moderation_decision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, moderator_id INT NOT NULL, target_kind VARCHAR(32) NOT NULL, target_id INT NOT NULL, action VARCHAR(32) NOT NULL, reason VARCHAR(1000) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_COMMUNITY_MODERATION_MODERATOR ON community_moderation_decision (moderator_id)');
        $this->addSql('CREATE INDEX idx_community_moderation_target ON community_moderation_decision (target_kind, target_id, created_at)');
        $this->addSql('ALTER TABLE community_moderation_decision ADD CONSTRAINT FK_COMMUNITY_MODERATION_MODERATOR FOREIGN KEY (moderator_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN community_moderation_decision.created_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE community_reaction');
        $this->addSql('DROP TABLE community_report');
        $this->addSql('DROP TABLE community_moderation_decision');
        $this->addSql('DROP TABLE community_comment');
    }
}
