<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260925000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add isolated patch-aware guides, structured builds, tier lists and review audit';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE game_guide (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, author_id INT DEFAULT NULL, reviewer_id INT DEFAULT NULL, title VARCHAR(180) NOT NULL, guide_type VARCHAR(24) NOT NULL, game_version VARCHAR(80) NOT NULL, season VARCHAR(80) NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, valid_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, review_status VARCHAR(16) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_GAME_GUIDE_VERSION ON game_guide (game_id, game_version, season)');
        $this->addSql('ALTER TABLE game_guide ADD CONSTRAINT FK_GAME_GUIDE_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_guide ADD CONSTRAINT FK_GAME_GUIDE_AUTHOR FOREIGN KEY (author_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_guide ADD CONSTRAINT FK_GAME_GUIDE_REVIEWER FOREIGN KEY (reviewer_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE game_guide_component (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guide_id INT NOT NULL, component_type VARCHAR(24) NOT NULL, component_key VARCHAR(120) NOT NULL, position INT NOT NULL, alternatives JSON NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAME_GUIDE_COMPONENT_POSITION ON game_guide_component (guide_id, position)');
        $this->addSql('ALTER TABLE game_guide_component ADD CONSTRAINT FK_GAME_GUIDE_COMPONENT FOREIGN KEY (guide_id) REFERENCES game_guide (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE game_guide_tier_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guide_id INT NOT NULL, entry_key VARCHAR(120) NOT NULL, tier VARCHAR(1) NOT NULL, reason TEXT NOT NULL, criteria TEXT NOT NULL, provenance VARCHAR(1000) NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAME_GUIDE_TIER_ENTRY ON game_guide_tier_entry (guide_id, entry_key)');
        $this->addSql('ALTER TABLE game_guide_tier_entry ADD CONSTRAINT FK_GAME_GUIDE_TIER FOREIGN KEY (guide_id) REFERENCES game_guide (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE game_guide_review_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guide_id INT NOT NULL, actor_id INT DEFAULT NULL, status VARCHAR(16) NOT NULL, reason VARCHAR(500) NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_GAME_GUIDE_REVIEW_AUDIT ON game_guide_review_audit (guide_id, occurred_at)');
        $this->addSql('ALTER TABLE game_guide_review_audit ADD CONSTRAINT FK_GAME_GUIDE_REVIEW_GUIDE FOREIGN KEY (guide_id) REFERENCES game_guide (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_guide_review_audit ADD CONSTRAINT FK_GAME_GUIDE_REVIEW_ACTOR FOREIGN KEY (actor_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(true, 'Guide revisions and review evidence require export and Trusted-approved restore handling before downgrade.');
    }
}
