<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260916200000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create pages and news content storage';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Migration can only be executed safely on PostgreSQL.',
        );

        $this->addSql('CREATE TABLE content_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, author_id INT NOT NULL, type VARCHAR(20) NOT NULL, title VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL, excerpt TEXT DEFAULT NULL, body TEXT NOT NULL, status VARCHAR(20) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_content_entry_slug ON content_entry (slug)');
        $this->addSql('CREATE INDEX IDX_CONTENT_ENTRY_AUTHOR ON content_entry (author_id)');
        $this->addSql('COMMENT ON COLUMN content_entry.published_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN content_entry.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN content_entry.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE content_entry ADD CONSTRAINT FK_CONTENT_ENTRY_AUTHOR FOREIGN KEY (author_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE content_entry');
    }
}
