<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260924220000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add isolated guild loot ledger, wishlist, award audit and vault inventory';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE guild_loot_ledger (id VARCHAR(64) NOT NULL, guild_id INT NOT NULL, member_id INT NOT NULL, actor_id INT DEFAULT NULL, amount INT NOT NULL, currency VARCHAR(8) NOT NULL, reason VARCHAR(500) NOT NULL, raid_reference VARCHAR(64) DEFAULT NULL, corrects_entry_id VARCHAR(64) DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_LOOT_LEDGER_MEMBER ON guild_loot_ledger (guild_id, member_id, currency, occurred_at)');
        $this->addSql('ALTER TABLE guild_loot_ledger ADD CONSTRAINT FK_LOOT_LEDGER_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_loot_ledger ADD CONSTRAINT FK_LOOT_LEDGER_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_loot_ledger ADD CONSTRAINT FK_LOOT_LEDGER_ACTOR FOREIGN KEY (actor_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_loot_ledger ADD CONSTRAINT FK_LOOT_LEDGER_CORRECTION FOREIGN KEY (corrects_entry_id) REFERENCES guild_loot_ledger (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE guild_loot_wishlist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, member_id INT NOT NULL, item_key VARCHAR(120) NOT NULL, priority SMALLINT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_LOOT_WISH ON guild_loot_wishlist (guild_id, member_id, item_key)');
        $this->addSql('ALTER TABLE guild_loot_wishlist ADD CONSTRAINT FK_LOOT_WISH_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_loot_wishlist ADD CONSTRAINT FK_LOOT_WISH_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE guild_loot_vault_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, item_key VARCHAR(120) NOT NULL, quantity INT NOT NULL, version INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_LOOT_VAULT_ITEM ON guild_loot_vault_entry (guild_id, item_key)');
        $this->addSql('ALTER TABLE guild_loot_vault_entry ADD CONSTRAINT FK_LOOT_VAULT_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE guild_loot_vault_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, actor_id INT DEFAULT NULL, item_key VARCHAR(120) NOT NULL, delta INT NOT NULL, reason VARCHAR(500) NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_LOOT_VAULT_AUDIT ON guild_loot_vault_audit (guild_id, occurred_at)');
        $this->addSql('ALTER TABLE guild_loot_vault_audit ADD CONSTRAINT FK_LOOT_VAULT_AUDIT_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_loot_vault_audit ADD CONSTRAINT FK_LOOT_VAULT_AUDIT_ACTOR FOREIGN KEY (actor_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(true, 'Loot and vault audit evidence is immutable; export and Trusted-approved restore handling are required before downgrade.');
    }
}
