<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260918170500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Persist sanitized local backup verification results';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('CREATE TABLE backup_verification_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, backup_id VARCHAR(40) NOT NULL, successful BOOLEAN NOT NULL, checked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_backup_verification_id ON backup_verification_status (backup_id)');
        $this->addSql("COMMENT ON COLUMN backup_verification_status.checked_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE backup_verification_status');
    }
}
