<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260924130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add guild characters, role needs, officer votes, onboarding, private notes and audited lifecycle history';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE guild_character (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, member_id INT NOT NULL, game_id INT NOT NULL, character_name VARCHAR(120) NOT NULL, character_class VARCHAR(100) DEFAULT NULL, role VARCHAR(80) DEFAULT NULL, main_character BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_CHARACTER_GUILD ON guild_character (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_CHARACTER_MEMBER ON guild_character (member_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_CHARACTER_GAME ON guild_character (game_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_guild_character_identity ON guild_character (guild_id, game_id, character_name)');
        $this->addSql('ALTER TABLE guild_character ADD CONSTRAINT FK_GUILD_CHARACTER_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_character ADD CONSTRAINT FK_GUILD_CHARACTER_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_character ADD CONSTRAINT FK_GUILD_CHARACTER_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE guild_role_need (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, game_id INT NOT NULL, role VARCHAR(80) NOT NULL, character_class VARCHAR(100) DEFAULT NULL, slots INT NOT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_ROLE_NEED_GUILD ON guild_role_need (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_ROLE_NEED_GAME ON guild_role_need (game_id)');
        $this->addSql('ALTER TABLE guild_role_need ADD CONSTRAINT FK_GUILD_ROLE_NEED_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_role_need ADD CONSTRAINT FK_GUILD_ROLE_NEED_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE guild_application_vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, voter_id INT NOT NULL, decision VARCHAR(12) NOT NULL, reason VARCHAR(1000) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_APPLICATION_VOTE_APPLICATION ON guild_application_vote (application_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_APPLICATION_VOTE_VOTER ON guild_application_vote (voter_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_guild_application_vote ON guild_application_vote (application_id, voter_id)');
        $this->addSql('ALTER TABLE guild_application_vote ADD CONSTRAINT FK_GUILD_APPLICATION_VOTE_APPLICATION FOREIGN KEY (application_id) REFERENCES guild_application (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_application_vote ADD CONSTRAINT FK_GUILD_APPLICATION_VOTE_VOTER FOREIGN KEY (voter_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_application_vote.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE guild_member_lifecycle_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, member_id INT NOT NULL, actor_id INT NOT NULL, action VARCHAR(24) NOT NULL, reason VARCHAR(1000) NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_LIFECYCLE_GUILD ON guild_member_lifecycle_event (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_LIFECYCLE_MEMBER_FK ON guild_member_lifecycle_event (member_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_LIFECYCLE_ACTOR ON guild_member_lifecycle_event (actor_id)');
        $this->addSql('CREATE INDEX idx_guild_member_lifecycle_member ON guild_member_lifecycle_event (member_id, created_at)');
        $this->addSql('ALTER TABLE guild_member_lifecycle_event ADD CONSTRAINT FK_GUILD_MEMBER_LIFECYCLE_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_member_lifecycle_event ADD CONSTRAINT FK_GUILD_MEMBER_LIFECYCLE_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_member_lifecycle_event ADD CONSTRAINT FK_GUILD_MEMBER_LIFECYCLE_ACTOR FOREIGN KEY (actor_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_member_lifecycle_event.starts_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN guild_member_lifecycle_event.ends_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN guild_member_lifecycle_event.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE guild_member_private_note (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, member_id INT NOT NULL, author_id INT NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_PRIVATE_NOTE_GUILD ON guild_member_private_note (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_PRIVATE_NOTE_MEMBER ON guild_member_private_note (member_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_PRIVATE_NOTE_AUTHOR ON guild_member_private_note (author_id)');
        $this->addSql('ALTER TABLE guild_member_private_note ADD CONSTRAINT FK_GUILD_MEMBER_PRIVATE_NOTE_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_member_private_note ADD CONSTRAINT FK_GUILD_MEMBER_PRIVATE_NOTE_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_member_private_note ADD CONSTRAINT FK_GUILD_MEMBER_PRIVATE_NOTE_AUTHOR FOREIGN KEY (author_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_member_private_note.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE guild_onboarding_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, member_id INT NOT NULL, completed_by_id INT DEFAULT NULL, label VARCHAR(180) NOT NULL, completed BOOLEAN DEFAULT false NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_ONBOARDING_GUILD ON guild_onboarding_task (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_ONBOARDING_MEMBER ON guild_onboarding_task (member_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_ONBOARDING_COMPLETED_BY ON guild_onboarding_task (completed_by_id)');
        $this->addSql('ALTER TABLE guild_onboarding_task ADD CONSTRAINT FK_GUILD_ONBOARDING_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_onboarding_task ADD CONSTRAINT FK_GUILD_ONBOARDING_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_onboarding_task ADD CONSTRAINT FK_GUILD_ONBOARDING_COMPLETED_BY FOREIGN KEY (completed_by_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_onboarding_task.completed_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE guild_onboarding_task');
        $this->addSql('DROP TABLE guild_member_private_note');
        $this->addSql('DROP TABLE guild_member_lifecycle_event');
        $this->addSql('DROP TABLE guild_application_vote');
        $this->addSql('DROP TABLE guild_role_need');
        $this->addSql('DROP TABLE guild_character');
    }
}
