<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260916223000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add per-module storage, media library, guild logos, members, applications and gaming module toggle';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');

        $this->addSql('CREATE TABLE module_storage_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, module_key VARCHAR(50) NOT NULL, storage_mode VARCHAR(10) NOT NULL, external_base_url VARCHAR(500) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_module_storage_key ON module_storage_setting (module_key)');
        $this->addSql('CREATE TABLE media_asset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, module_key VARCHAR(50) NOT NULL, storage_mode VARCHAR(10) NOT NULL, location VARCHAR(500) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(120) DEFAULT NULL, file_size INT DEFAULT NULL, alt_text VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql("COMMENT ON COLUMN media_asset.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('ALTER TABLE site_settings ADD gaming_enabled BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE guild ADD logo_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_GUILD_LOGO ON guild (logo_id)');
        $this->addSql('ALTER TABLE guild ADD CONSTRAINT FK_GUILD_LOGO FOREIGN KEY (logo_id) REFERENCES media_asset (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE guild_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, character_name VARCHAR(120) NOT NULL, rank_name VARCHAR(100) NOT NULL, character_class VARCHAR(100) DEFAULT NULL, character_level INT DEFAULT NULL, player_name VARCHAR(120) DEFAULT NULL, leader BOOLEAN DEFAULT false NOT NULL, active BOOLEAN DEFAULT true NOT NULL, position INT DEFAULT 0 NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_GUILD ON guild_member (guild_id)');
        $this->addSql('ALTER TABLE guild_member ADD CONSTRAINT FK_GUILD_MEMBER_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE guild_application (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, applicant_name VARCHAR(120) NOT NULL, email VARCHAR(180) NOT NULL, character_name VARCHAR(120) NOT NULL, character_class VARCHAR(100) DEFAULT NULL, message TEXT NOT NULL, status VARCHAR(10) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_APPLICATION_GUILD ON guild_application (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_APPLICATION_STATUS ON guild_application (status)');
        $this->addSql('ALTER TABLE guild_application ADD CONSTRAINT FK_GUILD_APPLICATION_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_application.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN guild_application.reviewed_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE guild_application');
        $this->addSql('DROP TABLE guild_member');
        $this->addSql('ALTER TABLE guild DROP CONSTRAINT FK_GUILD_LOGO');
        $this->addSql('DROP INDEX IDX_GUILD_LOGO');
        $this->addSql('ALTER TABLE guild DROP logo_id');
        $this->addSql('ALTER TABLE site_settings DROP gaming_enabled');
        $this->addSql('DROP TABLE media_asset');
        $this->addSql('DROP TABLE module_storage_setting');
    }
}
