<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260926100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add permission-aware modular search index with deterministic repair metadata';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql("CREATE TABLE search_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source_type VARCHAR(64) NOT NULL, source_id INT NOT NULL, module_key VARCHAR(64) NOT NULL, document_type VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, body TEXT NOT NULL, excerpt TEXT DEFAULT NULL, route VARCHAR(500) DEFAULT NULL, visibility VARCHAR(32) NOT NULL, owner_id INT DEFAULT NULL, guild_id INT DEFAULT NULL, facets JSON DEFAULT '[]' NOT NULL, popularity INT NOT NULL, recommendation_opt_out BOOLEAN DEFAULT false NOT NULL, fingerprint VARCHAR(64) NOT NULL, source_updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, indexed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_search_document_source ON search_document (source_type, source_id)');
        $this->addSql('CREATE INDEX IDX_SEARCH_DOCUMENT_MODULE_TYPE ON search_document (module_key, document_type)');
        $this->addSql('CREATE INDEX IDX_SEARCH_DOCUMENT_SOURCE_UPDATED ON search_document (source_updated_at)');
        $this->addSql("COMMENT ON COLUMN search_document.source_updated_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN search_document.indexed_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('DROP TABLE search_document');
    }
}
