<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260925060000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add private support cases, managed evidence, sanctions, appeals and retention evidence'; }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE support_case (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reporter_id INT DEFAULT NULL, assignee_id INT DEFAULT NULL, subject VARCHAR(180) NOT NULL, state VARCHAR(24) NOT NULL, version INT NOT NULL, deadline TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, legal_hold BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_SUPPORT_CASE_QUEUE ON support_case (state, deadline)');
        $this->addSql('ALTER TABLE support_case ADD CONSTRAINT FK_SUPPORT_CASE_REPORTER FOREIGN KEY (reporter_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE support_case ADD CONSTRAINT FK_SUPPORT_CASE_ASSIGNEE FOREIGN KEY (assignee_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE support_case_participant (case_id INT NOT NULL, user_id INT NOT NULL, participant_role VARCHAR(24) NOT NULL, PRIMARY KEY(case_id, user_id))");
        $this->addSql('ALTER TABLE support_case_participant ADD CONSTRAINT FK_SUPPORT_PART_CASE FOREIGN KEY (case_id) REFERENCES support_case (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE support_case_participant ADD CONSTRAINT FK_SUPPORT_PART_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE support_case_evidence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, case_id INT NOT NULL, owner_id INT DEFAULT NULL, reference_type VARCHAR(24) NOT NULL, reference_id INT NOT NULL, description TEXT NOT NULL, checksum VARCHAR(64) NOT NULL, explicitly_shared BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('ALTER TABLE support_case_evidence ADD CONSTRAINT FK_SUPPORT_EVIDENCE_CASE FOREIGN KEY (case_id) REFERENCES support_case (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE support_case_decision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, case_id INT NOT NULL, actor_id INT DEFAULT NULL, state VARCHAR(24) NOT NULL, reason VARCHAR(500) NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_SUPPORT_DECISION_HISTORY ON support_case_decision (case_id, occurred_at)');
        $this->addSql('ALTER TABLE support_case_decision ADD CONSTRAINT FK_SUPPORT_DECISION_CASE FOREIGN KEY (case_id) REFERENCES support_case (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE support_sanction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, case_id INT NOT NULL, subject_id INT DEFAULT NULL, sanction_type VARCHAR(24) NOT NULL, rule_reference VARCHAR(180) NOT NULL, reason TEXT NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('ALTER TABLE support_sanction ADD CONSTRAINT FK_SUPPORT_SANCTION_CASE FOREIGN KEY (case_id) REFERENCES support_case (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE support_appeal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sanction_id INT NOT NULL, appellant_id INT DEFAULT NULL, reviewer_id INT DEFAULT NULL, grounds TEXT NOT NULL, state VARCHAR(16) NOT NULL, decision_reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SUPPORT_APPEAL_SANCTION ON support_appeal (sanction_id, appellant_id)');
        $this->addSql('ALTER TABLE support_appeal ADD CONSTRAINT FK_SUPPORT_APPEAL_SANCTION FOREIGN KEY (sanction_id) REFERENCES support_sanction (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(true, 'Private case, evidence, sanction and appeal history requires export and Trusted-approved restore handling before downgrade.');
    }
}
