<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260925040000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add isolated forums, Q&A, guild rooms, subscriptions and moderation audit';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE forum_room (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT DEFAULT NULL, title VARCHAR(180) NOT NULL, visibility VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_FORUM_ROOM_GUILD ON forum_room (guild_id, visibility)');
        $this->addSql('ALTER TABLE forum_room ADD CONSTRAINT FK_FORUM_ROOM_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE forum_thread (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, room_id INT NOT NULL, author_id INT DEFAULT NULL, solved_post_id INT DEFAULT NULL, title VARCHAR(180) NOT NULL, state VARCHAR(16) NOT NULL, version INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_FORUM_THREAD_ROOM ON forum_thread (room_id, state, updated_at)');
        $this->addSql('ALTER TABLE forum_thread ADD CONSTRAINT FK_FORUM_THREAD_ROOM FOREIGN KEY (room_id) REFERENCES forum_room (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE forum_thread ADD CONSTRAINT FK_FORUM_THREAD_AUTHOR FOREIGN KEY (author_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE forum_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, thread_id INT NOT NULL, author_id INT DEFAULT NULL, quoted_post_id INT DEFAULT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, edited_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_FORUM_POST_THREAD ON forum_post (thread_id, created_at)');
        $this->addSql('ALTER TABLE forum_post ADD CONSTRAINT FK_FORUM_POST_THREAD FOREIGN KEY (thread_id) REFERENCES forum_thread (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE forum_post ADD CONSTRAINT FK_FORUM_POST_AUTHOR FOREIGN KEY (author_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE forum_post ADD CONSTRAINT FK_FORUM_POST_QUOTE FOREIGN KEY (quoted_post_id) REFERENCES forum_post (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE forum_thread ADD CONSTRAINT FK_FORUM_THREAD_SOLVED FOREIGN KEY (solved_post_id) REFERENCES forum_post (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE forum_mention (post_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(post_id, user_id))");
        $this->addSql('ALTER TABLE forum_mention ADD CONSTRAINT FK_FORUM_MENTION_POST FOREIGN KEY (post_id) REFERENCES forum_post (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE forum_mention ADD CONSTRAINT FK_FORUM_MENTION_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE forum_subscription (thread_id INT NOT NULL, user_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(thread_id, user_id))");
        $this->addSql('ALTER TABLE forum_subscription ADD CONSTRAINT FK_FORUM_SUB_THREAD FOREIGN KEY (thread_id) REFERENCES forum_thread (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE forum_subscription ADD CONSTRAINT FK_FORUM_SUB_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE forum_attachment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, post_id INT NOT NULL, owner_id INT DEFAULT NULL, reference_type VARCHAR(16) NOT NULL, reference_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_FORUM_ATTACHMENT_REF ON forum_attachment (reference_type, reference_id)');
        $this->addSql('ALTER TABLE forum_attachment ADD CONSTRAINT FK_FORUM_ATTACHMENT_POST FOREIGN KEY (post_id) REFERENCES forum_post (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE forum_moderation_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, thread_id INT NOT NULL, actor_id INT DEFAULT NULL, state VARCHAR(16) NOT NULL, reason VARCHAR(500) NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_FORUM_MOD_AUDIT ON forum_moderation_audit (thread_id, occurred_at)');
        $this->addSql('ALTER TABLE forum_moderation_audit ADD CONSTRAINT FK_FORUM_MOD_THREAD FOREIGN KEY (thread_id) REFERENCES forum_thread (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE forum_moderation_audit ADD CONSTRAINT FK_FORUM_MOD_ACTOR FOREIGN KEY (actor_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(true, 'Forum moderation, private-room and attachment evidence requires export and Trusted-approved restore handling before downgrade.');
    }
}
