<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260925050000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add hardware products, typed specifications, benchmark methodology, revisions and community setups'; }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE hardware_product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, category VARCHAR(80) NOT NULL, manufacturer VARCHAR(160) NOT NULL, disclosure TEXT NOT NULL, published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE hardware_specification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT NOT NULL, spec_key VARCHAR(120) NOT NULL, value JSON NOT NULL, unit VARCHAR(32) NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_HARDWARE_SPEC ON hardware_specification (product_id, spec_key)');
        $this->addSql('ALTER TABLE hardware_specification ADD CONSTRAINT FK_HARDWARE_SPEC_PRODUCT FOREIGN KEY (product_id) REFERENCES hardware_product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE hardware_benchmark_methodology (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, version VARCHAR(80) NOT NULL, procedure TEXT NOT NULL, test_system JSON NOT NULL, disclosure TEXT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE hardware_benchmark_measurement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT NOT NULL, methodology_id INT NOT NULL, series VARCHAR(180) NOT NULL, value DOUBLE PRECISION NOT NULL, unit VARCHAR(32) NOT NULL, sample_count INT NOT NULL, source_type VARCHAR(16) NOT NULL, measured_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_HARDWARE_BENCHMARK_SERIES ON hardware_benchmark_measurement (series, unit)');
        $this->addSql('ALTER TABLE hardware_benchmark_measurement ADD CONSTRAINT FK_HARDWARE_BENCHMARK_PRODUCT FOREIGN KEY (product_id) REFERENCES hardware_product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hardware_benchmark_measurement ADD CONSTRAINT FK_HARDWARE_BENCHMARK_METHOD FOREIGN KEY (methodology_id) REFERENCES hardware_benchmark_methodology (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE hardware_product_revision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT NOT NULL, actor_id INT DEFAULT NULL, version INT NOT NULL, summary VARCHAR(500) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_HARDWARE_REVISION_VERSION ON hardware_product_revision (product_id, version)');
        $this->addSql('ALTER TABLE hardware_product_revision ADD CONSTRAINT FK_HARDWARE_REVISION_PRODUCT FOREIGN KEY (product_id) REFERENCES hardware_product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE hardware_product_revision ADD CONSTRAINT FK_HARDWARE_REVISION_ACTOR FOREIGN KEY (actor_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE hardware_community_setup (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT DEFAULT NULL, product_ids JSON NOT NULL, notes TEXT NOT NULL, moderated BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('ALTER TABLE hardware_community_setup ADD CONSTRAINT FK_HARDWARE_SETUP_OWNER FOREIGN KEY (owner_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(true, 'Benchmark methodology, disclosure and revision evidence requires export and Trusted-approved restore handling before downgrade.');
    }
}
