<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260925020000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add safe gameserver registry, cached public status and outage history';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE game_server_registry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, name VARCHAR(160) NOT NULL, public_host VARCHAR(253) NOT NULL, public_port INT NOT NULL, protocol VARCHAR(32) NOT NULL, enabled BOOLEAN NOT NULL, maintenance BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAME_SERVER_TARGET ON game_server_registry (public_host, public_port, protocol)');
        $this->addSql('ALTER TABLE game_server_registry ADD CONSTRAINT FK_GAME_SERVER_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE game_server_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, server_id INT NOT NULL, state VARCHAR(16) NOT NULL, players INT NOT NULL, slots INT NOT NULL, ping_ms INT DEFAULT NULL, map_name VARCHAR(160) DEFAULT NULL, server_version VARCHAR(120) DEFAULT NULL, observed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_GAME_SERVER_STATUS_CURRENT ON game_server_status (server_id, observed_at)');
        $this->addSql('ALTER TABLE game_server_status ADD CONSTRAINT FK_GAME_SERVER_STATUS_SERVER FOREIGN KEY (server_id) REFERENCES game_server_registry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE game_server_outage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, server_id INT NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_GAME_SERVER_OUTAGE_HISTORY ON game_server_outage (server_id, started_at)');
        $this->addSql('ALTER TABLE game_server_outage ADD CONSTRAINT FK_GAME_SERVER_OUTAGE_SERVER FOREIGN KEY (server_id) REFERENCES game_server_registry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE game_server_alert_subscription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, server_id INT NOT NULL, user_id INT NOT NULL, outage_alert BOOLEAN NOT NULL, recovery_alert BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAME_SERVER_ALERT_USER ON game_server_alert_subscription (server_id, user_id)');
        $this->addSql('ALTER TABLE game_server_alert_subscription ADD CONSTRAINT FK_GAME_SERVER_ALERT_SERVER FOREIGN KEY (server_id) REFERENCES game_server_registry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_server_alert_subscription ADD CONSTRAINT FK_GAME_SERVER_ALERT_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(true, 'Outage history and alert subscriptions require export and Trusted-approved restore handling before downgrade.');
    }
}
