<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260918162500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Queue durable retries for failed optional media replicas';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('CREATE TABLE media_replication_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, media_asset_id INT NOT NULL, target_key VARCHAR(64) NOT NULL, provider_key VARCHAR(64) NOT NULL, object_key VARCHAR(500) NOT NULL, staged_filename VARCHAR(80) NOT NULL, attempts INT NOT NULL, last_attempt_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_MEDIA_REPLICATION_ASSET ON media_replication_task (media_asset_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_media_replication_target ON media_replication_task (media_asset_id, target_key)');
        $this->addSql("COMMENT ON COLUMN media_replication_task.last_attempt_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN media_replication_task.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('ALTER TABLE media_replication_task ADD CONSTRAINT FK_MEDIA_REPLICATION_ASSET FOREIGN KEY (media_asset_id) REFERENCES media_asset (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE media_replication_task');
    }
}
