<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20260919100000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add content approval scheduling and immutable revision history'; }
    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql("ALTER TABLE content_entry ADD scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
        $this->addSql("COMMENT ON COLUMN content_entry.scheduled_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("CREATE TABLE content_revision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entry_id INT NOT NULL, created_by_id INT NOT NULL, revision_number INT NOT NULL, type VARCHAR(20) NOT NULL, title VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL, excerpt TEXT DEFAULT NULL, body TEXT NOT NULL, status VARCHAR(20) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_CONTENT_REVISION_ENTRY ON content_revision (entry_id)");
        $this->addSql("CREATE INDEX IDX_CONTENT_REVISION_AUTHOR ON content_revision (created_by_id)");
        $this->addSql("CREATE UNIQUE INDEX uniq_content_revision_number ON content_revision (entry_id, revision_number)");
        $this->addSql("COMMENT ON COLUMN content_revision.published_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN content_revision.scheduled_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN content_revision.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("ALTER TABLE content_revision ADD CONSTRAINT FK_CONTENT_REVISION_ENTRY FOREIGN KEY (entry_id) REFERENCES content_entry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE content_revision ADD CONSTRAINT FK_CONTENT_REVISION_AUTHOR FOREIGN KEY (created_by_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE");
    }
    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('DROP TABLE content_revision');
        $this->addSql('ALTER TABLE content_entry DROP scheduled_at');
    }
}
