<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260917010000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add encrypted Discord integrations for guilds'; }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('CREATE TABLE guild_discord_integration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, encrypted_webhook_url TEXT NOT NULL, enabled BOOLEAN DEFAULT FALSE NOT NULL, notify_events BOOLEAN DEFAULT TRUE NOT NULL, notify_announcements BOOLEAN DEFAULT TRUE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GUILD_DISCORD_INTEGRATION_GUILD ON guild_discord_integration (guild_id)');
        $this->addSql('ALTER TABLE guild_discord_integration ADD CONSTRAINT FK_GUILD_DISCORD_INTEGRATION_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_discord_integration.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN guild_discord_integration.updated_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE guild_discord_integration');
    }
}
