<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260916213000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add games and guilds'; }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('CREATE TABLE game (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, description TEXT DEFAULT NULL, website_url VARCHAR(500) DEFAULT NULL, enabled BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_game_slug ON game (slug)');
        $this->addSql('CREATE TABLE guild (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, server_name VARCHAR(120) NOT NULL, region VARCHAR(60) DEFAULT NULL, faction VARCHAR(80) DEFAULT NULL, description TEXT NOT NULL, website_url VARCHAR(500) DEFAULT NULL, recruitment_open BOOLEAN DEFAULT false NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_guild_slug ON guild (slug)');
        $this->addSql('CREATE INDEX IDX_GUILD_GAME ON guild (game_id)');
        $this->addSql('ALTER TABLE guild ADD CONSTRAINT FK_GUILD_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild.created_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE guild');
        $this->addSql('DROP TABLE game');
    }
}
