<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260919160000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add guild teams, application review workflow and event attendance'; }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');

        $this->addSql("CREATE TABLE guild_team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, leader_id INT DEFAULT NULL, name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, color VARCHAR(7) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_GUILD_TEAM_GUILD ON guild_team (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_TEAM_LEADER ON guild_team (leader_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_guild_team_name ON guild_team (guild_id, name)');
        $this->addSql('ALTER TABLE guild_team ADD CONSTRAINT FK_GUILD_TEAM_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_team ADD CONSTRAINT FK_GUILD_TEAM_LEADER FOREIGN KEY (leader_id) REFERENCES guild_member (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_team.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE guild_team_member (guild_team_id INT NOT NULL, guild_member_id INT NOT NULL, PRIMARY KEY(guild_team_id, guild_member_id))');
        $this->addSql('CREATE INDEX IDX_GUILD_TEAM_MEMBER_TEAM ON guild_team_member (guild_team_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_TEAM_MEMBER_MEMBER ON guild_team_member (guild_member_id)');
        $this->addSql('ALTER TABLE guild_team_member ADD CONSTRAINT FK_GUILD_TEAM_MEMBER_TEAM FOREIGN KEY (guild_team_id) REFERENCES guild_team (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_team_member ADD CONSTRAINT FK_GUILD_TEAM_MEMBER_MEMBER FOREIGN KEY (guild_member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE guild_event ADD team_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_GUILD_EVENT_TEAM ON guild_event (team_id)');
        $this->addSql('ALTER TABLE guild_event ADD CONSTRAINT FK_GUILD_EVENT_TEAM FOREIGN KEY (team_id) REFERENCES guild_team (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("ALTER TABLE guild_event_signup ADD attendance VARCHAR(20) DEFAULT 'unknown' NOT NULL");
        $this->addSql('ALTER TABLE guild_event_signup ADD attendance_checked_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE guild_event_signup ADD attendance_checked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_SIGNUP_ATTENDANCE_CHECKER ON guild_event_signup (attendance_checked_by_id)');
        $this->addSql('ALTER TABLE guild_event_signup ADD CONSTRAINT FK_SIGNUP_ATTENDANCE_CHECKER FOREIGN KEY (attendance_checked_by_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_event_signup.attendance_checked_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('ALTER TABLE guild_application ADD assigned_to_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE guild_application ADD internal_notes TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE guild_application ALTER status TYPE VARCHAR(12)');
        $this->addSql('CREATE INDEX IDX_GUILD_APPLICATION_ASSIGNEE ON guild_application (assigned_to_id)');
        $this->addSql('ALTER TABLE guild_application ADD CONSTRAINT FK_GUILD_APPLICATION_ASSIGNEE FOREIGN KEY (assigned_to_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('ALTER TABLE guild_application DROP CONSTRAINT FK_GUILD_APPLICATION_ASSIGNEE');
        $this->addSql('ALTER TABLE guild_application DROP assigned_to_id');
        $this->addSql('ALTER TABLE guild_application DROP internal_notes');
        $this->addSql('ALTER TABLE guild_application ALTER status TYPE VARCHAR(10)');
        $this->addSql('ALTER TABLE guild_event_signup DROP CONSTRAINT FK_SIGNUP_ATTENDANCE_CHECKER');
        $this->addSql('ALTER TABLE guild_event_signup DROP attendance');
        $this->addSql('ALTER TABLE guild_event_signup DROP attendance_checked_by_id');
        $this->addSql('ALTER TABLE guild_event_signup DROP attendance_checked_at');
        $this->addSql('ALTER TABLE guild_event DROP CONSTRAINT FK_GUILD_EVENT_TEAM');
        $this->addSql('ALTER TABLE guild_event DROP team_id');
        $this->addSql('DROP TABLE guild_team_member');
        $this->addSql('DROP TABLE guild_team');
    }
}
