<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260917012000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add email verification and expiring account tokens'; }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('ALTER TABLE cms_user ADD email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql("COMMENT ON COLUMN cms_user.email_verified_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('UPDATE cms_user SET email_verified_at = CURRENT_TIMESTAMP');
        $this->addSql('CREATE TABLE account_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, purpose VARCHAR(40) NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ACCOUNT_TOKEN_USER ON account_token (user_id)');
        $this->addSql('CREATE INDEX IDX_ACCOUNT_TOKEN_LOOKUP ON account_token (token_hash, purpose)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ACCOUNT_TOKEN_HASH ON account_token (token_hash)');
        $this->addSql('ALTER TABLE account_token ADD CONSTRAINT FK_ACCOUNT_TOKEN_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN account_token.expires_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN account_token.used_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN account_token.created_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE account_token');
        $this->addSql('ALTER TABLE cms_user DROP email_verified_at');
    }
}
