<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260925030000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add isolated galleries, licensed submissions, competition windows and audited votes';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE gallery_album (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT DEFAULT NULL, title VARCHAR(180) NOT NULL, visibility VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('ALTER TABLE gallery_album ADD CONSTRAINT FK_GALLERY_ALBUM_OWNER FOREIGN KEY (owner_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE gallery_submission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, album_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, moderator_id INT DEFAULT NULL, media_asset_id INT NOT NULL, title VARCHAR(180) NOT NULL, license VARCHAR(160) NOT NULL, credit VARCHAR(300) NOT NULL, visibility VARCHAR(16) NOT NULL, status VARCHAR(16) NOT NULL, decision_reason VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_GALLERY_SUBMISSION_STATUS ON gallery_submission (status, visibility)');
        $this->addSql('ALTER TABLE gallery_submission ADD CONSTRAINT FK_GALLERY_SUBMISSION_ALBUM FOREIGN KEY (album_id) REFERENCES gallery_album (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gallery_submission ADD CONSTRAINT FK_GALLERY_SUBMISSION_OWNER FOREIGN KEY (owner_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gallery_submission ADD CONSTRAINT FK_GALLERY_SUBMISSION_MODERATOR FOREIGN KEY (moderator_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gallery_submission ADD CONSTRAINT FK_GALLERY_SUBMISSION_MEDIA FOREIGN KEY (media_asset_id) REFERENCES media_asset (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE gallery_competition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, submissions_open_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, submissions_close_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, voting_open_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, voting_close_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE gallery_competition_entry (competition_id INT NOT NULL, submission_id INT NOT NULL, PRIMARY KEY(competition_id, submission_id))");
        $this->addSql('ALTER TABLE gallery_competition_entry ADD CONSTRAINT FK_GALLERY_ENTRY_COMPETITION FOREIGN KEY (competition_id) REFERENCES gallery_competition (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gallery_competition_entry ADD CONSTRAINT FK_GALLERY_ENTRY_SUBMISSION FOREIGN KEY (submission_id) REFERENCES gallery_submission (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE gallery_competition_vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, competition_id INT NOT NULL, submission_id INT NOT NULL, user_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GALLERY_COMPETITION_VOTER ON gallery_competition_vote (competition_id, user_id)');
        $this->addSql('ALTER TABLE gallery_competition_vote ADD CONSTRAINT FK_GALLERY_VOTE_COMPETITION FOREIGN KEY (competition_id) REFERENCES gallery_competition (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gallery_competition_vote ADD CONSTRAINT FK_GALLERY_VOTE_SUBMISSION FOREIGN KEY (submission_id) REFERENCES gallery_submission (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE gallery_competition_vote ADD CONSTRAINT FK_GALLERY_VOTE_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE gallery_vote_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, competition_id INT NOT NULL, user_id INT DEFAULT NULL, actor_id INT DEFAULT NULL, from_submission_id INT DEFAULT NULL, to_submission_id INT DEFAULT NULL, reason VARCHAR(500) NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_GALLERY_VOTE_AUDIT ON gallery_vote_audit (competition_id, occurred_at)');
        $this->addSql('ALTER TABLE gallery_vote_audit ADD CONSTRAINT FK_GALLERY_AUDIT_COMPETITION FOREIGN KEY (competition_id) REFERENCES gallery_competition (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(true, 'Gallery licence, moderation and vote audit evidence requires export and Trusted-approved restore handling before downgrade.');
    }
}
