<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260917006000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add security audit log'; }
    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('CREATE TABLE audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, actor_id INT DEFAULT NULL, action VARCHAR(80) NOT NULL, subject_type VARCHAR(120) NOT NULL, subject_id INT DEFAULT NULL, summary VARCHAR(255) NOT NULL, context JSON NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AUDIT_ACTOR ON audit_log (actor_id)');
        $this->addSql('CREATE INDEX IDX_AUDIT_CREATED ON audit_log (created_at)');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT FK_AUDIT_ACTOR FOREIGN KEY (actor_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN audit_log.created_at IS '(DC2Type:datetime_immutable)'");
    }
    public function down(Schema $schema): void { $this->addSql('DROP TABLE audit_log'); }
}
