<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260924210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add isolated recurring guild-event planning, signup queue and immutable attendance evidence';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE guild_event_series (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, title VARCHAR(180) NOT NULL, event_type VARCHAR(24) NOT NULL, timezone VARCHAR(64) NOT NULL, frequency VARCHAR(16) NOT NULL, occurrence_limit INT NOT NULL, preparation_notes TEXT DEFAULT NULL, preparation_visibility VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_EVENT_SERIES_GUILD ON guild_event_series (guild_id)');
        $this->addSql('ALTER TABLE guild_event_series ADD CONSTRAINT FK_EVENT_SERIES_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE guild_event_occurrence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, series_id INT NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, role_capacities JSON NOT NULL, visibility VARCHAR(16) NOT NULL, reminder_minutes INT DEFAULT NULL, vod_reference VARCHAR(255) DEFAULT NULL, vod_visibility VARCHAR(16) NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_EVENT_OCCURRENCE_SERIES ON guild_event_occurrence (series_id)');
        $this->addSql('ALTER TABLE guild_event_occurrence ADD CONSTRAINT FK_EVENT_OCCURRENCE_SERIES FOREIGN KEY (series_id) REFERENCES guild_event_series (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE guild_event_planning_signup (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, occurrence_id INT NOT NULL, member_id INT NOT NULL, requested_role VARCHAR(32) NOT NULL, status VARCHAR(16) NOT NULL, queue_position INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EVENT_PLANNING_MEMBER ON guild_event_planning_signup (occurrence_id, member_id)');
        $this->addSql('ALTER TABLE guild_event_planning_signup ADD CONSTRAINT FK_EVENT_PLANNING_OCCURRENCE FOREIGN KEY (occurrence_id) REFERENCES guild_event_occurrence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_event_planning_signup ADD CONSTRAINT FK_EVENT_PLANNING_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("CREATE TABLE guild_event_attendance_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, occurrence_id INT NOT NULL, member_id INT NOT NULL, actor_id INT DEFAULT NULL, status VARCHAR(16) NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, evidence_note TEXT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_EVENT_ATTENDANCE_LOOKUP ON guild_event_attendance_history (occurrence_id, member_id, occurred_at)');
        $this->addSql('ALTER TABLE guild_event_attendance_history ADD CONSTRAINT FK_EVENT_ATTENDANCE_OCCURRENCE FOREIGN KEY (occurrence_id) REFERENCES guild_event_occurrence (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_event_attendance_history ADD CONSTRAINT FK_EVENT_ATTENDANCE_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_event_attendance_history ADD CONSTRAINT FK_EVENT_ATTENDANCE_ACTOR FOREIGN KEY (actor_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(true, 'Attendance history is immutable operational evidence; export and Trusted-approved restore handling are required before downgrade.');
    }
}
