<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260917005000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add guild events, signups and internal announcements'; }
    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('CREATE TABLE guild_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, created_by_id INT DEFAULT NULL, title VARCHAR(180) NOT NULL, type VARCHAR(20) NOT NULL, description TEXT NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, max_participants INT DEFAULT NULL, role_limits JSON NOT NULL, location VARCHAR(140) DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_EVENT_GUILD ON guild_event (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_EVENT_CREATOR ON guild_event (created_by_id)');
        $this->addSql('ALTER TABLE guild_event ADD CONSTRAINT FK_GUILD_EVENT_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_event ADD CONSTRAINT FK_GUILD_EVENT_CREATOR FOREIGN KEY (created_by_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_event.starts_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN guild_event.ends_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN guild_event.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE guild_event_signup (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_id INT NOT NULL, member_id INT NOT NULL, user_id INT NOT NULL, response VARCHAR(20) NOT NULL, role VARCHAR(20) NOT NULL, note TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_event_member_signup ON guild_event_signup (event_id, member_id)');
        $this->addSql('CREATE INDEX IDX_SIGNUP_EVENT ON guild_event_signup (event_id)');
        $this->addSql('CREATE INDEX IDX_SIGNUP_MEMBER ON guild_event_signup (member_id)');
        $this->addSql('CREATE INDEX IDX_SIGNUP_USER ON guild_event_signup (user_id)');
        $this->addSql('ALTER TABLE guild_event_signup ADD CONSTRAINT FK_SIGNUP_EVENT FOREIGN KEY (event_id) REFERENCES guild_event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_event_signup ADD CONSTRAINT FK_SIGNUP_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_event_signup ADD CONSTRAINT FK_SIGNUP_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_event_signup.updated_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE guild_announcement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, author_id INT DEFAULT NULL, title VARCHAR(180) NOT NULL, body TEXT NOT NULL, pinned BOOLEAN DEFAULT false NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ANNOUNCEMENT_GUILD ON guild_announcement (guild_id)');
        $this->addSql('CREATE INDEX IDX_ANNOUNCEMENT_AUTHOR ON guild_announcement (author_id)');
        $this->addSql('ALTER TABLE guild_announcement ADD CONSTRAINT FK_ANNOUNCEMENT_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_announcement ADD CONSTRAINT FK_ANNOUNCEMENT_AUTHOR FOREIGN KEY (author_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_announcement.published_at IS '(DC2Type:datetime_immutable)'");
    }
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE guild_event_signup');
        $this->addSql('DROP TABLE guild_announcement');
        $this->addSql('DROP TABLE guild_event');
    }
}
