<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260918060000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add provider-neutral external connector target definitions';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');

        $this->addSql('CREATE TABLE external_connector_target (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, capability VARCHAR(40) NOT NULL, target_key VARCHAR(64) NOT NULL, provider_key VARCHAR(64) NOT NULL, display_name VARCHAR(120) NOT NULL, enabled BOOLEAN DEFAULT FALSE NOT NULL, is_required BOOLEAN DEFAULT TRUE NOT NULL, priority INT DEFAULT 100 NOT NULL, configuration_reference VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_connector_capability_key ON external_connector_target (capability, target_key)');
        $this->addSql('CREATE INDEX idx_connector_capability_enabled ON external_connector_target (capability, enabled, priority)');
        $this->addSql("COMMENT ON COLUMN external_connector_target.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN external_connector_target.updated_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE external_connector_target');
    }
}
