<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261002225000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add private persistent News Editor block snippet library'; }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('CREATE TABLE news_block_snippet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, label VARCHAR(80) NOT NULL, block JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_NEWS_BLOCK_SNIPPET_OWNER ON news_block_snippet (owner_id)');
        $this->addSql('CREATE INDEX idx_news_block_snippet_owner_updated ON news_block_snippet (owner_id, updated_at)');
        $this->addSql('ALTER TABLE news_block_snippet ADD CONSTRAINT FK_NEWS_BLOCK_SNIPPET_OWNER FOREIGN KEY (owner_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN news_block_snippet.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN news_block_snippet.updated_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('DROP TABLE news_block_snippet');
    }
}
