<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260924130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add supplemental guild character, onboarding and private-note records';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE guild_character (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, member_id INT NOT NULL, game_id INT NOT NULL, character_name VARCHAR(120) NOT NULL, character_class VARCHAR(100) DEFAULT NULL, role VARCHAR(80) DEFAULT NULL, main_character BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_CHARACTER_ENTITY_GUILD ON guild_character (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_CHARACTER_ENTITY_MEMBER ON guild_character (member_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_CHARACTER_ENTITY_GAME ON guild_character (game_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_guild_character_identity ON guild_character (guild_id, game_id, character_name)');
        $this->addSql('ALTER TABLE guild_character ADD CONSTRAINT FK_GUILD_CHARACTER_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_character ADD CONSTRAINT FK_GUILD_CHARACTER_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_character ADD CONSTRAINT FK_GUILD_CHARACTER_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE guild_member_private_note (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, member_id INT NOT NULL, author_id INT NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_PRIVATE_NOTE_GUILD ON guild_member_private_note (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_PRIVATE_NOTE_MEMBER ON guild_member_private_note (member_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_PRIVATE_NOTE_AUTHOR ON guild_member_private_note (author_id)');
        $this->addSql('ALTER TABLE guild_member_private_note ADD CONSTRAINT FK_GUILD_MEMBER_PRIVATE_NOTE_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_member_private_note ADD CONSTRAINT FK_GUILD_MEMBER_PRIVATE_NOTE_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_member_private_note ADD CONSTRAINT FK_GUILD_MEMBER_PRIVATE_NOTE_AUTHOR FOREIGN KEY (author_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_member_private_note.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE guild_onboarding_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, member_id INT NOT NULL, completed_by_id INT DEFAULT NULL, label VARCHAR(180) NOT NULL, completed BOOLEAN DEFAULT false NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_ONBOARDING_GUILD ON guild_onboarding_task (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_ONBOARDING_MEMBER ON guild_onboarding_task (member_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_ONBOARDING_COMPLETED_BY ON guild_onboarding_task (completed_by_id)');
        $this->addSql('ALTER TABLE guild_onboarding_task ADD CONSTRAINT FK_GUILD_ONBOARDING_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_onboarding_task ADD CONSTRAINT FK_GUILD_ONBOARDING_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_onboarding_task ADD CONSTRAINT FK_GUILD_ONBOARDING_COMPLETED_BY FOREIGN KEY (completed_by_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_onboarding_task.completed_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE guild_onboarding_task');
        $this->addSql('DROP TABLE guild_member_private_note');
        $this->addSql('DROP TABLE guild_character');
    }
}
