<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260919140000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add reusable access roles, timed account locks and revocable sessions'; }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');

        $this->addSql("CREATE TABLE access_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role_key VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, permissions JSON NOT NULL, active BOOLEAN DEFAULT true NOT NULL, system_role BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_access_role_key ON access_role (role_key)');
        $this->addSql("COMMENT ON COLUMN access_role.permissions IS '(DC2Type:json)'");
        $this->addSql("COMMENT ON COLUMN access_role.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE cms_user_access_role (user_id INT NOT NULL, access_role_id INT NOT NULL, PRIMARY KEY(user_id, access_role_id))');
        $this->addSql('CREATE INDEX IDX_USER_ACCESS_ROLE_USER ON cms_user_access_role (user_id)');
        $this->addSql('CREATE INDEX IDX_USER_ACCESS_ROLE_ROLE ON cms_user_access_role (access_role_id)');
        $this->addSql('ALTER TABLE cms_user_access_role ADD CONSTRAINT FK_USER_ACCESS_ROLE_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cms_user_access_role ADD CONSTRAINT FK_USER_ACCESS_ROLE_ROLE FOREIGN KEY (access_role_id) REFERENCES access_role (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE cms_user ADD locked_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE cms_user ADD lock_reason VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cms_user ADD security_version INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE cms_user ADD last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE cms_user ADD last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        foreach (['locked_until', 'last_login_at', 'last_seen_at'] as $column) {
            $this->addSql("COMMENT ON COLUMN cms_user.$column IS '(DC2Type:datetime_immutable)'");
        }

        $this->addSql("CREATE TABLE user_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, session_hash VARCHAR(64) NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, security_version INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_user_session_hash ON user_session (session_hash)');
        $this->addSql('CREATE INDEX IDX_USER_SESSION_USER ON user_session (user_id)');
        $this->addSql('CREATE INDEX IDX_USER_SESSION_ACTIVE ON user_session (user_id, revoked_at)');
        $this->addSql('ALTER TABLE user_session ADD CONSTRAINT FK_USER_SESSION_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        foreach (['created_at', 'last_seen_at', 'revoked_at'] as $column) {
            $this->addSql("COMMENT ON COLUMN user_session.$column IS '(DC2Type:datetime_immutable)'");
        }

        $this->addSql("INSERT INTO access_role (role_key, name, description, permissions, active, system_role, created_at) VALUES ('editor', 'Redaktion', 'Seiten, News und Medien verwalten', '[\"CMS_CONTENT_MANAGE\",\"CMS_STORAGE_MANAGE\"]', true, true, NOW())");
        $this->addSql("INSERT INTO access_role (role_key, name, description, permissions, active, system_role, created_at) VALUES ('community', 'Community-Verwaltung', 'Gaming, Gilden und Videos verwalten', '[\"CMS_GAMING_MANAGE\",\"CMS_VIDEO_MANAGE\"]', true, true, NOW())");
        $this->addSql("INSERT INTO access_role (role_key, name, description, permissions, active, system_role, created_at) VALUES ('operations', 'Systembetrieb', 'Schnittstellen, Speicher und Einstellungen verwalten', '[\"CMS_CONNECTORS_MANAGE\",\"CMS_STORAGE_MANAGE\",\"CMS_SETTINGS_MANAGE\",\"CMS_AUDIT_VIEW\"]', true, true, NOW())");
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('DROP TABLE user_session');
        $this->addSql('DROP TABLE cms_user_access_role');
        $this->addSql('DROP TABLE access_role');
        $this->addSql('ALTER TABLE cms_user DROP locked_until');
        $this->addSql('ALTER TABLE cms_user DROP lock_reason');
        $this->addSql('ALTER TABLE cms_user DROP security_version');
        $this->addSql('ALTER TABLE cms_user DROP last_login_at');
        $this->addSql('ALTER TABLE cms_user DROP last_seen_at');
    }
}
