<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260919120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add media folders, rich metadata, checksums and update tracking';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');

        $this->addSql("CREATE TABLE media_folder (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_media_folder_slug ON media_folder (slug)');
        $this->addSql('CREATE INDEX IDX_MEDIA_FOLDER_PARENT ON media_folder (parent_id)');
        $this->addSql("COMMENT ON COLUMN media_folder.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('ALTER TABLE media_folder ADD CONSTRAINT FK_MEDIA_FOLDER_PARENT FOREIGN KEY (parent_id) REFERENCES media_folder (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE media_asset ADD folder_id INT DEFAULT NULL');
        $this->addSql("ALTER TABLE media_asset ADD title VARCHAR(180) DEFAULT NULL");
        $this->addSql('ALTER TABLE media_asset ADD caption TEXT DEFAULT NULL');
        $this->addSql("ALTER TABLE media_asset ADD tags JSON DEFAULT '[]' NOT NULL");
        $this->addSql('ALTER TABLE media_asset ADD checksum_sha256 VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE media_asset ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('UPDATE media_asset SET title = original_name, updated_at = created_at');
        $this->addSql('ALTER TABLE media_asset ALTER title SET NOT NULL');
        $this->addSql('ALTER TABLE media_asset ALTER updated_at SET NOT NULL');
        $this->addSql("COMMENT ON COLUMN media_asset.tags IS '(DC2Type:json)'");
        $this->addSql("COMMENT ON COLUMN media_asset.updated_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('CREATE INDEX IDX_MEDIA_ASSET_FOLDER ON media_asset (folder_id)');
        $this->addSql('CREATE INDEX IDX_MEDIA_ASSET_CHECKSUM ON media_asset (checksum_sha256)');
        $this->addSql('ALTER TABLE media_asset ADD CONSTRAINT FK_MEDIA_ASSET_FOLDER FOREIGN KEY (folder_id) REFERENCES media_folder (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('ALTER TABLE media_asset DROP CONSTRAINT FK_MEDIA_ASSET_FOLDER');
        $this->addSql('DROP TABLE media_folder');
        $this->addSql('ALTER TABLE media_asset DROP folder_id');
        $this->addSql('ALTER TABLE media_asset DROP title');
        $this->addSql('ALTER TABLE media_asset DROP caption');
        $this->addSql('ALTER TABLE media_asset DROP tags');
        $this->addSql('ALTER TABLE media_asset DROP checksum_sha256');
        $this->addSql('ALTER TABLE media_asset DROP updated_at');
    }
}
