<?php

declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20260920203000 extends AbstractMigration
{
    public function getDescription(): string { return 'Expand content into editorial publishing with tags, releases, redirects, SEO, trash and scheduled unpublishing'; }
    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql("ALTER TABLE content_entry ADD subtitle VARCHAR(220) DEFAULT NULL, ADD scheduled_unpublish_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ADD trashed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ADD featured BOOLEAN DEFAULT false NOT NULL, ADD pinned BOOLEAN DEFAULT false NOT NULL, ADD unlisted BOOLEAN DEFAULT false NOT NULL, ADD seo_title VARCHAR(180) DEFAULT NULL, ADD seo_description VARCHAR(320) DEFAULT NULL, ADD canonical_url VARCHAR(500) DEFAULT NULL, ADD no_index BOOLEAN DEFAULT false NOT NULL");
        $this->addSql("COMMENT ON COLUMN content_entry.scheduled_unpublish_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN content_entry.trashed_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("CREATE INDEX IDX_CONTENT_ENTRY_STATUS_PUBLISH ON content_entry (status, published_at)");
        $this->addSql("CREATE INDEX IDX_CONTENT_ENTRY_SCHEDULED_UNPUBLISH ON content_entry (scheduled_unpublish_at)");
        $this->addSql("ALTER TABLE content_category ADD parent_id INT DEFAULT NULL");
        $this->addSql("CREATE INDEX IDX_CONTENT_CATEGORY_PARENT ON content_category (parent_id)");
        $this->addSql("ALTER TABLE content_category ADD CONSTRAINT FK_CONTENT_CATEGORY_PARENT FOREIGN KEY (parent_id) REFERENCES content_category (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE TABLE content_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX uniq_content_tag_slug ON content_tag (slug)");
        $this->addSql("CREATE TABLE content_entry_tag (content_entry_id INT NOT NULL, content_tag_id INT NOT NULL, PRIMARY KEY(content_entry_id, content_tag_id))");
        $this->addSql("CREATE INDEX IDX_CONTENT_ENTRY_TAG_ENTRY ON content_entry_tag (content_entry_id)"); $this->addSql("CREATE INDEX IDX_CONTENT_ENTRY_TAG_TAG ON content_entry_tag (content_tag_id)");
        $this->addSql("ALTER TABLE content_entry_tag ADD CONSTRAINT FK_CONTENT_ENTRY_TAG_ENTRY FOREIGN KEY (content_entry_id) REFERENCES content_entry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE content_entry_tag ADD CONSTRAINT FK_CONTENT_ENTRY_TAG_TAG FOREIGN KEY (content_tag_id) REFERENCES content_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE TABLE content_redirect (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entry_id INT NOT NULL, type VARCHAR(20) NOT NULL, source_slug VARCHAR(200) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_CONTENT_REDIRECT_ENTRY ON content_redirect (entry_id)"); $this->addSql("CREATE UNIQUE INDEX uniq_content_redirect_source ON content_redirect (type, source_slug)");
        $this->addSql("COMMENT ON COLUMN content_redirect.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("ALTER TABLE content_redirect ADD CONSTRAINT FK_CONTENT_REDIRECT_ENTRY FOREIGN KEY (entry_id) REFERENCES content_entry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE TABLE content_release (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by_id INT NOT NULL, name VARCHAR(160) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_CONTENT_RELEASE_CREATED_BY ON content_release (created_by_id)"); $this->addSql("CREATE INDEX IDX_CONTENT_RELEASE_SCHEDULE ON content_release (status, scheduled_at)");
        $this->addSql("COMMENT ON COLUMN content_release.scheduled_at IS '(DC2Type:datetime_immutable)'"); $this->addSql("COMMENT ON COLUMN content_release.published_at IS '(DC2Type:datetime_immutable)'"); $this->addSql("COMMENT ON COLUMN content_release.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("ALTER TABLE content_release ADD CONSTRAINT FK_CONTENT_RELEASE_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE TABLE content_release_entry (content_release_id INT NOT NULL, content_entry_id INT NOT NULL, PRIMARY KEY(content_release_id, content_entry_id))");
        $this->addSql("CREATE INDEX IDX_CONTENT_RELEASE_ENTRY_RELEASE ON content_release_entry (content_release_id)"); $this->addSql("CREATE INDEX IDX_CONTENT_RELEASE_ENTRY_ENTRY ON content_release_entry (content_entry_id)");
        $this->addSql("ALTER TABLE content_release_entry ADD CONSTRAINT FK_CONTENT_RELEASE_ENTRY_RELEASE FOREIGN KEY (content_release_id) REFERENCES content_release (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE content_release_entry ADD CONSTRAINT FK_CONTENT_RELEASE_ENTRY_ENTRY FOREIGN KEY (content_entry_id) REFERENCES content_entry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE content_revision ADD subtitle VARCHAR(220) DEFAULT NULL, ADD scheduled_unpublish_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ADD category_id INT DEFAULT NULL, ADD tag_slugs JSON DEFAULT '[]' NOT NULL, ADD featured BOOLEAN DEFAULT false NOT NULL, ADD pinned BOOLEAN DEFAULT false NOT NULL, ADD unlisted BOOLEAN DEFAULT false NOT NULL, ADD seo_title VARCHAR(180) DEFAULT NULL, ADD seo_description VARCHAR(320) DEFAULT NULL, ADD canonical_url VARCHAR(500) DEFAULT NULL, ADD no_index BOOLEAN DEFAULT false NOT NULL");
        $this->addSql("COMMENT ON COLUMN content_revision.scheduled_unpublish_at IS '(DC2Type:datetime_immutable)'"); $this->addSql("CREATE INDEX IDX_CONTENT_REVISION_CATEGORY ON content_revision (category_id)");
        $this->addSql("ALTER TABLE content_revision ADD CONSTRAINT FK_CONTENT_REVISION_CATEGORY FOREIGN KEY (category_id) REFERENCES content_category (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE");
    }
    public function down(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql("ALTER TABLE content_revision DROP CONSTRAINT FK_CONTENT_REVISION_CATEGORY");
        $this->addSql("ALTER TABLE content_revision DROP subtitle, DROP scheduled_unpublish_at, DROP category_id, DROP tag_slugs, DROP featured, DROP pinned, DROP unlisted, DROP seo_title, DROP seo_description, DROP canonical_url, DROP no_index");
        $this->addSql("DROP TABLE content_release_entry"); $this->addSql("DROP TABLE content_release"); $this->addSql("DROP TABLE content_redirect"); $this->addSql("DROP TABLE content_entry_tag"); $this->addSql("DROP TABLE content_tag");
        $this->addSql("ALTER TABLE content_category DROP CONSTRAINT FK_CONTENT_CATEGORY_PARENT"); $this->addSql("ALTER TABLE content_category DROP parent_id");
        $this->addSql("ALTER TABLE content_entry DROP subtitle, DROP scheduled_unpublish_at, DROP trashed_at, DROP featured, DROP pinned, DROP unlisted, DROP seo_title, DROP seo_description, DROP canonical_url, DROP no_index");
    }
}
