<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260924123000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add guild roster, recruitment voting, trials, private notes and lifecycle history';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE guild_character_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, member_id INT NOT NULL, game_id INT NOT NULL, character_name VARCHAR(120) NOT NULL, character_class VARCHAR(100) DEFAULT NULL, role VARCHAR(40) DEFAULT NULL, main_character BOOLEAN DEFAULT false NOT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_CHARACTER_GUILD ON guild_character_profile (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_CHARACTER_MEMBER ON guild_character_profile (member_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_CHARACTER_GAME ON guild_character_profile (game_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_guild_character_name ON guild_character_profile (guild_id, game_id, character_name)');
        $this->addSql('ALTER TABLE guild_character_profile ADD CONSTRAINT FK_GUILD_CHARACTER_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_character_profile ADD CONSTRAINT FK_GUILD_CHARACTER_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_character_profile ADD CONSTRAINT FK_GUILD_CHARACTER_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE guild_role_need (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, game_id INT NOT NULL, role_key VARCHAR(40) NOT NULL, class_key VARCHAR(100) NOT NULL, desired_count INT DEFAULT 0 NOT NULL, active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_ROLE_NEED_GUILD ON guild_role_need (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_ROLE_NEED_GAME ON guild_role_need (game_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_guild_role_need ON guild_role_need (guild_id, game_id, role_key, class_key)');
        $this->addSql('ALTER TABLE guild_role_need ADD CONSTRAINT FK_GUILD_ROLE_NEED_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_role_need ADD CONSTRAINT FK_GUILD_ROLE_NEED_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE guild_recruitment_case (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, guild_id INT NOT NULL, decided_by_id INT DEFAULT NULL, status VARCHAR(16) NOT NULL, decision_reason VARCHAR(1000) DEFAULT NULL, trial_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, appeal_message TEXT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_guild_recruitment_application ON guild_recruitment_case (application_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_RECRUITMENT_GUILD ON guild_recruitment_case (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_RECRUITMENT_DECIDED_BY ON guild_recruitment_case (decided_by_id)');
        $this->addSql('ALTER TABLE guild_recruitment_case ADD CONSTRAINT FK_GUILD_RECRUITMENT_APPLICATION FOREIGN KEY (application_id) REFERENCES guild_application (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_recruitment_case ADD CONSTRAINT FK_GUILD_RECRUITMENT_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_recruitment_case ADD CONSTRAINT FK_GUILD_RECRUITMENT_DECIDED_BY FOREIGN KEY (decided_by_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_recruitment_case.trial_expires_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN guild_recruitment_case.updated_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE guild_application_vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, guild_id INT NOT NULL, voter_id INT NOT NULL, decision VARCHAR(16) NOT NULL, reason VARCHAR(1000) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_APPLICATION_VOTE_APPLICATION ON guild_application_vote (application_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_APPLICATION_VOTE_GUILD ON guild_application_vote (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_APPLICATION_VOTE_VOTER ON guild_application_vote (voter_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_guild_application_vote ON guild_application_vote (application_id, voter_id)');
        $this->addSql('ALTER TABLE guild_application_vote ADD CONSTRAINT FK_GUILD_APPLICATION_VOTE_APPLICATION FOREIGN KEY (application_id) REFERENCES guild_application (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_application_vote ADD CONSTRAINT FK_GUILD_APPLICATION_VOTE_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_application_vote ADD CONSTRAINT FK_GUILD_APPLICATION_VOTE_VOTER FOREIGN KEY (voter_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_application_vote.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE guild_member_lifecycle_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, member_id INT NOT NULL, actor_id INT NOT NULL, action VARCHAR(24) NOT NULL, reason VARCHAR(1000) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_LIFECYCLE_GUILD ON guild_member_lifecycle_event (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_LIFECYCLE_MEMBER ON guild_member_lifecycle_event (member_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_LIFECYCLE_ACTOR ON guild_member_lifecycle_event (actor_id)');
        $this->addSql('CREATE INDEX idx_guild_member_lifecycle ON guild_member_lifecycle_event (guild_id, member_id, created_at)');
        $this->addSql('ALTER TABLE guild_member_lifecycle_event ADD CONSTRAINT FK_GUILD_MEMBER_LIFECYCLE_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_member_lifecycle_event ADD CONSTRAINT FK_GUILD_MEMBER_LIFECYCLE_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_member_lifecycle_event ADD CONSTRAINT FK_GUILD_MEMBER_LIFECYCLE_ACTOR FOREIGN KEY (actor_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_member_lifecycle_event.created_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE guild_private_member_note (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, member_id INT NOT NULL, author_id INT NOT NULL, note TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_PRIVATE_NOTE_GUILD ON guild_private_member_note (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_PRIVATE_NOTE_MEMBER ON guild_private_member_note (member_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_PRIVATE_NOTE_AUTHOR ON guild_private_member_note (author_id)');
        $this->addSql('CREATE INDEX idx_guild_private_note_timeline ON guild_private_member_note (guild_id, member_id, created_at)');
        $this->addSql('ALTER TABLE guild_private_member_note ADD CONSTRAINT FK_GUILD_PRIVATE_NOTE_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_private_member_note ADD CONSTRAINT FK_GUILD_PRIVATE_NOTE_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_private_member_note ADD CONSTRAINT FK_GUILD_PRIVATE_NOTE_AUTHOR FOREIGN KEY (author_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_private_member_note.created_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE guild_application_vote');
        $this->addSql('DROP TABLE guild_private_member_note');
        $this->addSql('DROP TABLE guild_member_lifecycle_event');
        $this->addSql('DROP TABLE guild_recruitment_case');
        $this->addSql('DROP TABLE guild_role_need');
        $this->addSql('DROP TABLE guild_character_profile');
    }
}
