<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260925010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add private character accounts, progression profiles, visibility consent and import provenance';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE game_character_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, game_id INT NOT NULL, account_key VARCHAR(160) NOT NULL, display_name VARCHAR(160) NOT NULL, source VARCHAR(16) NOT NULL, consent_version INT DEFAULT 1 NOT NULL, consent_granted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GAME_CHARACTER_ACCOUNT_OWNER ON game_character_account (owner_id)');
        $this->addSql('CREATE INDEX IDX_GAME_CHARACTER_ACCOUNT_GAME ON game_character_account (game_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAME_CHARACTER_ACCOUNT_OWNER_GAME_KEY ON game_character_account (owner_id, game_id, account_key)');
        $this->addSql('ALTER TABLE game_character_account ADD CONSTRAINT FK_GAME_CHARACTER_ACCOUNT_OWNER FOREIGN KEY (owner_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_character_account ADD CONSTRAINT FK_GAME_CHARACTER_ACCOUNT_GAME FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN game_character_account.consent_granted_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN game_character_account.deleted_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN game_character_account.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN game_character_account.updated_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE game_character_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, account_id INT NOT NULL, main_profile_id INT DEFAULT NULL, external_id VARCHAR(160) DEFAULT NULL, name VARCHAR(160) NOT NULL, server VARCHAR(120) DEFAULT NULL, region VARCHAR(80) DEFAULT NULL, character_class VARCHAR(100) DEFAULT NULL, role VARCHAR(80) DEFAULT NULL, level INT DEFAULT NULL, builds JSON NOT NULL, professions JSON NOT NULL, progression JSON NOT NULL, collections JSON NOT NULL, source VARCHAR(16) NOT NULL, visibility_default BOOLEAN DEFAULT false NOT NULL, refresh_version INT DEFAULT 0 NOT NULL, last_imported_hash VARCHAR(128) DEFAULT NULL, last_imported_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GAME_CHARACTER_PROFILE_ACCOUNT ON game_character_profile (account_id)');
        $this->addSql('CREATE INDEX IDX_GAME_CHARACTER_PROFILE_MAIN ON game_character_profile (main_profile_id)');
        $this->addSql('CREATE INDEX IDX_GAME_CHARACTER_PROFILE_VISIBILITY ON game_character_profile (visibility_default, deleted_at)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAME_CHARACTER_PROFILE_EXTERNAL ON game_character_profile (account_id, external_id)');
        $this->addSql('ALTER TABLE game_character_profile ADD CONSTRAINT FK_GAME_CHARACTER_PROFILE_ACCOUNT FOREIGN KEY (account_id) REFERENCES game_character_account (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game_character_profile ADD CONSTRAINT FK_GAME_CHARACTER_PROFILE_MAIN FOREIGN KEY (main_profile_id) REFERENCES game_character_profile (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN game_character_profile.last_imported_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN game_character_profile.deleted_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN game_character_profile.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN game_character_profile.updated_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE game_character_field_consent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, profile_id INT NOT NULL, field_key VARCHAR(40) NOT NULL, granted BOOLEAN DEFAULT false NOT NULL, source VARCHAR(30) NOT NULL, granted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GAME_CHARACTER_FIELD_CONSENT_PROFILE ON game_character_field_consent (profile_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAME_CHARACTER_FIELD_CONSENT ON game_character_field_consent (profile_id, field_key)');
        $this->addSql('ALTER TABLE game_character_field_consent ADD CONSTRAINT FK_GAME_CHARACTER_FIELD_CONSENT_PROFILE FOREIGN KEY (profile_id) REFERENCES game_character_profile (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN game_character_field_consent.granted_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN game_character_field_consent.revoked_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE game_character_import_provenance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, profile_id INT NOT NULL, provider VARCHAR(80) NOT NULL, external_id VARCHAR(160) NOT NULL, payload_hash VARCHAR(128) NOT NULL, status VARCHAR(16) NOT NULL, observed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, metadata JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GAME_CHARACTER_IMPORT_PROFILE_OBSERVED ON game_character_import_provenance (profile_id, observed_at)');
        $this->addSql('ALTER TABLE game_character_import_provenance ADD CONSTRAINT FK_GAME_CHARACTER_IMPORT_PROFILE FOREIGN KEY (profile_id) REFERENCES game_character_profile (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN game_character_import_provenance.observed_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE game_character_import_provenance');
        $this->addSql('DROP TABLE game_character_field_consent');
        $this->addSql('DROP TABLE game_character_profile');
        $this->addSql('DROP TABLE game_character_account');
    }
}
