<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260917001000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add guild ranks, application questions, linked characters and admin notifications'; }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');

        $this->addSql("CREATE TABLE guild_rank (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(7) DEFAULT NULL, position INT DEFAULT 0 NOT NULL, default_rank BOOLEAN DEFAULT false NOT NULL, permissions JSON NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_GUILD_RANK_GUILD ON guild_rank (guild_id)');
        $this->addSql('ALTER TABLE guild_rank ADD CONSTRAINT FK_GUILD_RANK_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("CREATE TABLE guild_application_question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, label VARCHAR(255) NOT NULL, help_text TEXT DEFAULT NULL, type VARCHAR(20) NOT NULL, required BOOLEAN DEFAULT false NOT NULL, position INT DEFAULT 0 NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_GUILD_QUESTION_GUILD ON guild_application_question (guild_id)');
        $this->addSql('ALTER TABLE guild_application_question ADD CONSTRAINT FK_GUILD_QUESTION_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("CREATE TABLE admin_notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(60) NOT NULL, title VARCHAR(180) NOT NULL, message TEXT NOT NULL, link VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("COMMENT ON COLUMN admin_notification.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN admin_notification.read_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('ALTER TABLE guild_member ADD user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE guild_member ADD rank_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_USER ON guild_member (user_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_MEMBER_RANK ON guild_member (rank_id)');
        $this->addSql('ALTER TABLE guild_member ADD CONSTRAINT FK_GUILD_MEMBER_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_member ADD CONSTRAINT FK_GUILD_MEMBER_RANK FOREIGN KEY (rank_id) REFERENCES guild_rank (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("ALTER TABLE guild_application ADD answers JSON DEFAULT '[]' NOT NULL");
        $this->addSql('ALTER TABLE guild_application ALTER answers DROP DEFAULT');
        $this->addSql('ALTER TABLE guild_application ADD converted_member_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_GUILD_APPLICATION_MEMBER ON guild_application (converted_member_id)');
        $this->addSql('ALTER TABLE guild_application ADD CONSTRAINT FK_GUILD_APPLICATION_MEMBER FOREIGN KEY (converted_member_id) REFERENCES guild_member (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE guild_application DROP CONSTRAINT FK_GUILD_APPLICATION_MEMBER');
        $this->addSql('ALTER TABLE guild_application DROP converted_member_id');
        $this->addSql('ALTER TABLE guild_application DROP answers');
        $this->addSql('ALTER TABLE guild_member DROP CONSTRAINT FK_GUILD_MEMBER_USER');
        $this->addSql('ALTER TABLE guild_member DROP CONSTRAINT FK_GUILD_MEMBER_RANK');
        $this->addSql('ALTER TABLE guild_member DROP user_id');
        $this->addSql('ALTER TABLE guild_member DROP rank_id');
        $this->addSql('DROP TABLE admin_notification');
        $this->addSql('DROP TABLE guild_application_question');
        $this->addSql('DROP TABLE guild_rank');
    }
}
