<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260926020000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add private social conversations, relationships, blocks, retention and moderation evidence';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE social_conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by_id INT NOT NULL, type VARCHAR(12) NOT NULL, title VARCHAR(180) DEFAULT NULL, retention_days INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_message_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_SOCIAL_CONVERSATION_CREATED_BY ON social_conversation (created_by_id)');
        $this->addSql('CREATE INDEX idx_social_conversation_activity ON social_conversation (last_message_at)');
        $this->addSql('ALTER TABLE social_conversation ADD CONSTRAINT FK_SOCIAL_CONVERSATION_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN social_conversation.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN social_conversation.updated_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN social_conversation.last_message_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN social_conversation.deleted_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE social_conversation_participant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conversation_id INT NOT NULL, user_id INT NOT NULL, role VARCHAR(12) NOT NULL, status VARCHAR(12) NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, left_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_social_participant ON social_conversation_participant (conversation_id, user_id)');
        $this->addSql('CREATE INDEX idx_social_participant_user_status ON social_conversation_participant (user_id, status)');
        $this->addSql('CREATE INDEX IDX_SOCIAL_PARTICIPANT_CONVERSATION ON social_conversation_participant (conversation_id)');
        $this->addSql('ALTER TABLE social_conversation_participant ADD CONSTRAINT FK_SOCIAL_PARTICIPANT_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES social_conversation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_conversation_participant ADD CONSTRAINT FK_SOCIAL_PARTICIPANT_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN social_conversation_participant.joined_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN social_conversation_participant.left_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN social_conversation_participant.last_read_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE social_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conversation_id INT NOT NULL, author_id INT NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, edited_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deletion_reason VARCHAR(500) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_social_message_conversation_created ON social_message (conversation_id, created_at)');
        $this->addSql('CREATE INDEX idx_social_message_author_created ON social_message (author_id, created_at)');
        $this->addSql('ALTER TABLE social_message ADD CONSTRAINT FK_SOCIAL_MESSAGE_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES social_conversation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_message ADD CONSTRAINT FK_SOCIAL_MESSAGE_AUTHOR FOREIGN KEY (author_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN social_message.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN social_message.edited_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN social_message.deleted_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE social_attachment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message_id INT NOT NULL, uploaded_by_id INT NOT NULL, storage_locator VARCHAR(500) NOT NULL, original_name VARCHAR(180) NOT NULL, mime_type VARCHAR(120) NOT NULL, file_size INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_social_attachment_message ON social_attachment (message_id)');
        $this->addSql('CREATE INDEX IDX_SOCIAL_ATTACHMENT_UPLOADED_BY ON social_attachment (uploaded_by_id)');
        $this->addSql('ALTER TABLE social_attachment ADD CONSTRAINT FK_SOCIAL_ATTACHMENT_MESSAGE FOREIGN KEY (message_id) REFERENCES social_message (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_attachment ADD CONSTRAINT FK_SOCIAL_ATTACHMENT_UPLOADED_BY FOREIGN KEY (uploaded_by_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN social_attachment.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN social_attachment.revoked_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE social_block (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, blocker_id INT NOT NULL, blocked_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lifted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_social_block_pair ON social_block (blocker_id, blocked_id)');
        $this->addSql('CREATE INDEX idx_social_block_blocked ON social_block (blocked_id, lifted_at)');
        $this->addSql('ALTER TABLE social_block ADD CONSTRAINT FK_SOCIAL_BLOCK_BLOCKER FOREIGN KEY (blocker_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_block ADD CONSTRAINT FK_SOCIAL_BLOCK_BLOCKED FOREIGN KEY (blocked_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN social_block.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN social_block.lifted_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE social_relationship (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, requester_id INT NOT NULL, recipient_id INT NOT NULL, type VARCHAR(12) NOT NULL, state VARCHAR(12) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, responded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_social_relationship_pair ON social_relationship (requester_id, recipient_id, type)');
        $this->addSql('CREATE INDEX idx_social_relationship_recipient_state ON social_relationship (recipient_id, state)');
        $this->addSql('CREATE INDEX idx_social_relationship_requester_state ON social_relationship (requester_id, state)');
        $this->addSql('ALTER TABLE social_relationship ADD CONSTRAINT FK_SOCIAL_RELATIONSHIP_REQUESTER FOREIGN KEY (requester_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_relationship ADD CONSTRAINT FK_SOCIAL_RELATIONSHIP_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN social_relationship.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN social_relationship.responded_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE social_privacy_settings (user_id INT NOT NULL, message_policy VARCHAR(16) NOT NULL, relationship_policy VARCHAR(16) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(user_id))');
        $this->addSql('ALTER TABLE social_privacy_settings ADD CONSTRAINT FK_SOCIAL_PRIVACY_USER FOREIGN KEY (user_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN social_privacy_settings.updated_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE social_report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message_id INT NOT NULL, reporter_id INT NOT NULL, moderator_id INT DEFAULT NULL, reason VARCHAR(32) NOT NULL, details TEXT DEFAULT NULL, status VARCHAR(16) NOT NULL, decision_reason VARCHAR(1000) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_social_report_queue ON social_report (status, created_at)');
        $this->addSql('CREATE INDEX IDX_SOCIAL_REPORT_MESSAGE ON social_report (message_id)');
        $this->addSql('CREATE INDEX IDX_SOCIAL_REPORT_REPORTER ON social_report (reporter_id)');
        $this->addSql('CREATE INDEX IDX_SOCIAL_REPORT_MODERATOR ON social_report (moderator_id)');
        $this->addSql('ALTER TABLE social_report ADD CONSTRAINT FK_SOCIAL_REPORT_MESSAGE FOREIGN KEY (message_id) REFERENCES social_message (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_report ADD CONSTRAINT FK_SOCIAL_REPORT_REPORTER FOREIGN KEY (reporter_id) REFERENCES cms_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_report ADD CONSTRAINT FK_SOCIAL_REPORT_MODERATOR FOREIGN KEY (moderator_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN social_report.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql("COMMENT ON COLUMN social_report.decided_at IS '(DC2Type:datetime_immutable)'");

        $this->addSql('CREATE TABLE social_moderation_decision (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, target_kind VARCHAR(32) NOT NULL, target_id INT NOT NULL, moderator_id INT NOT NULL, action VARCHAR(32) NOT NULL, reason VARCHAR(1000) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_social_moderation_target ON social_moderation_decision (target_kind, target_id, created_at)');
        $this->addSql('ALTER TABLE social_moderation_decision ADD CONSTRAINT FK_SOCIAL_MODERATION_MODERATOR FOREIGN KEY (moderator_id) REFERENCES cms_user (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN social_moderation_decision.created_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE social_moderation_decision');
        $this->addSql('DROP TABLE social_report');
        $this->addSql('DROP TABLE social_privacy_settings');
        $this->addSql('DROP TABLE social_relationship');
        $this->addSql('DROP TABLE social_block');
        $this->addSql('DROP TABLE social_attachment');
        $this->addSql('DROP TABLE social_message');
        $this->addSql('DROP TABLE social_conversation_participant');
        $this->addSql('DROP TABLE social_conversation');
    }
}
