<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260924130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add supplemental guild onboarding tasks';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE guild_onboarding_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, guild_id INT NOT NULL, member_id INT NOT NULL, completed_by_id INT DEFAULT NULL, label VARCHAR(180) NOT NULL, completed BOOLEAN DEFAULT false NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_GUILD_ONBOARDING_GUILD ON guild_onboarding_task (guild_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_ONBOARDING_MEMBER ON guild_onboarding_task (member_id)');
        $this->addSql('CREATE INDEX IDX_GUILD_ONBOARDING_COMPLETED_BY ON guild_onboarding_task (completed_by_id)');
        $this->addSql('ALTER TABLE guild_onboarding_task ADD CONSTRAINT FK_GUILD_ONBOARDING_GUILD FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_onboarding_task ADD CONSTRAINT FK_GUILD_ONBOARDING_MEMBER FOREIGN KEY (member_id) REFERENCES guild_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guild_onboarding_task ADD CONSTRAINT FK_GUILD_ONBOARDING_COMPLETED_BY FOREIGN KEY (completed_by_id) REFERENCES cms_user (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("COMMENT ON COLUMN guild_onboarding_task.completed_at IS '(DC2Type:datetime_immutable)'");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE guild_onboarding_task');
    }
}
