<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260918131500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add non-secret per-target media replica records';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('CREATE TABLE media_asset_replica (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, media_asset_id INT NOT NULL, target_key VARCHAR(64) NOT NULL, provider_key VARCHAR(64) NOT NULL, object_key VARCHAR(500) NOT NULL, location VARCHAR(500) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_MEDIA_REPLICA_ASSET ON media_asset_replica (media_asset_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_media_replica_target ON media_asset_replica (media_asset_id, target_key)');
        $this->addSql("COMMENT ON COLUMN media_asset_replica.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('ALTER TABLE media_asset_replica ADD CONSTRAINT FK_MEDIA_REPLICA_ASSET FOREIGN KEY (media_asset_id) REFERENCES media_asset (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE media_asset_replica');
    }
}
