<?php

declare(strict_types=1);

namespace VideoWorkspaceMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261001045000 extends AbstractMigration
{
    public function getDescription(): string { return 'Add independent video sources and authorized live playback without modifying existing video data'; }
    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'PostgreSQL required.');
        $this->addSql('CREATE TABLE video_workspace_source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, video_id INT DEFAULT NULL, creator_id INT DEFAULT NULL, label VARCHAR(160) NOT NULL, provider VARCHAR(32) NOT NULL, url VARCHAR(700) NOT NULL, enabled BOOLEAN NOT NULL, position INT NOT NULL, authorized BOOLEAN NOT NULL, version INT NOT NULL DEFAULT 1, starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_vworkspace_video_position ON video_workspace_source (video_id, position, id)');
        $this->addSql('CREATE INDEX IDX_VWORKSPACE_CREATOR ON video_workspace_source (creator_id)');
        $this->addSql('ALTER TABLE video_workspace_source ADD CONSTRAINT FK_VWORKSPACE_VIDEO FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_workspace_source ADD CONSTRAINT FK_VWORKSPACE_CREATOR FOREIGN KEY (creator_id) REFERENCES video_discovery_creator (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
    public function down(Schema $schema): void
    {
        $this->abortIf((int) $this->connection->fetchOne('SELECT COUNT(*) FROM video_workspace_source') > 0, 'Export video sources before downgrade; populated source data must not be discarded.');
        $this->addSql('DROP TABLE video_workspace_source');
    }
}
